/**
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 0.1
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;


/**
 * Autostellplatz
 */

public class Autostellplatz   {
  @JsonProperty("mieteinnahmenMonatlich")
  private BigDecimal mieteinnahmenMonatlich = null;

  /**
   * Gets or Sets typ
   */
  public enum TypEnum {
    STELLPLATZ("STELLPLATZ"),
    
    CARPORT("CARPORT"),
    
    GARAGE("GARAGE"),
    
    DOPPEL_GARAGE("DOPPEL_GARAGE"),
    
    KELLER_GARAGE("KELLER_GARAGE"),
    
    TIEFGARAGEN_STELLPLATZ("TIEFGARAGEN_STELLPLATZ");

    private String value;

    TypEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypEnum fromValue(String text) {
      for (TypEnum b : TypEnum.values()) {
          if (String.valueOf(b.value).equals(text)) {
              return b;
          }
      }
      return null;
    }
  }

  @JsonProperty("typ")
  private TypEnum typ = null;

  public Autostellplatz mieteinnahmenMonatlich(BigDecimal mieteinnahmenMonatlich) {
    this.mieteinnahmenMonatlich = mieteinnahmenMonatlich;
    return this;
  }

   /**
   * Get mieteinnahmenMonatlich
   * @return mieteinnahmenMonatlich
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getMieteinnahmenMonatlich() {
    return mieteinnahmenMonatlich;
  }

  public void setMieteinnahmenMonatlich(BigDecimal mieteinnahmenMonatlich) {
    this.mieteinnahmenMonatlich = mieteinnahmenMonatlich;
  }

  public Autostellplatz typ(TypEnum typ) {
    this.typ = typ;
    return this;
  }

   /**
   * Get typ
   * @return typ
  **/
  @ApiModelProperty(example = "null", value = "")
  public TypEnum getTyp() {
    return typ;
  }

  public void setTyp(TypEnum typ) {
    this.typ = typ;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Autostellplatz autostellplatz = (Autostellplatz) o;
    return Objects.equals(this.mieteinnahmenMonatlich, autostellplatz.mieteinnahmenMonatlich) &&
        Objects.equals(this.typ, autostellplatz.typ);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mieteinnahmenMonatlich, typ);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Autostellplatz {\n");
    
    sb.append("    mieteinnahmenMonatlich: ").append(toIndentedString(mieteinnahmenMonatlich)).append("\n");
    sb.append("    typ: ").append(toIndentedString(typ)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

