/*
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 0.1
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import de.europace.eli.model.ProduktAnbieter;
import de.europace.eli.model.SparPhase;
import de.europace.eli.model.TilgungsPhase;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.joda.time.LocalDate;

/**
 * BausparAngebot
 */

public class BausparAngebot {
  @JsonProperty("abschlussGebuehr")
  private BigDecimal abschlussGebuehr = null;

  @JsonProperty("angebotsHinweisFuerAntragsteller")
  private String angebotsHinweisFuerAntragsteller = null;

  @JsonProperty("bausparSumme")
  private BigDecimal bausparSumme = null;

  @JsonProperty("einmalzahlung")
  private BigDecimal einmalzahlung = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("produktAnbieter")
  private ProduktAnbieter produktAnbieter = null;

  @JsonProperty("sparPhase")
  private SparPhase sparPhase = null;

  @JsonProperty("tarif")
  private String tarif = null;

  @JsonProperty("tilgungsPhase")
  private TilgungsPhase tilgungsPhase = null;

  @JsonProperty("vertragsBeginn")
  private LocalDate vertragsBeginn = null;

  @JsonProperty("vertragsNummer")
  private String vertragsNummer = null;

  @JsonProperty("verwaltungsgebuehrenJaehrlich")
  private BigDecimal verwaltungsgebuehrenJaehrlich = null;

  @JsonProperty("zuteilungsDatum")
  private LocalDate zuteilungsDatum = null;

  public BausparAngebot abschlussGebuehr(BigDecimal abschlussGebuehr) {
    this.abschlussGebuehr = abschlussGebuehr;
    return this;
  }

   /**
   * Get abschlussGebuehr
   * @return abschlussGebuehr
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getAbschlussGebuehr() {
    return abschlussGebuehr;
  }

  public void setAbschlussGebuehr(BigDecimal abschlussGebuehr) {
    this.abschlussGebuehr = abschlussGebuehr;
  }

  public BausparAngebot angebotsHinweisFuerAntragsteller(String angebotsHinweisFuerAntragsteller) {
    this.angebotsHinweisFuerAntragsteller = angebotsHinweisFuerAntragsteller;
    return this;
  }

   /**
   * nur bei neuen extern berechneten Bausparverträgen und bei Gegenangeboten
   * @return angebotsHinweisFuerAntragsteller
  **/
  @ApiModelProperty(example = "null", value = "nur bei neuen extern berechneten Bausparverträgen und bei Gegenangeboten")
  public String getAngebotsHinweisFuerAntragsteller() {
    return angebotsHinweisFuerAntragsteller;
  }

  public void setAngebotsHinweisFuerAntragsteller(String angebotsHinweisFuerAntragsteller) {
    this.angebotsHinweisFuerAntragsteller = angebotsHinweisFuerAntragsteller;
  }

  public BausparAngebot bausparSumme(BigDecimal bausparSumme) {
    this.bausparSumme = bausparSumme;
    return this;
  }

   /**
   * Get bausparSumme
   * @return bausparSumme
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getBausparSumme() {
    return bausparSumme;
  }

  public void setBausparSumme(BigDecimal bausparSumme) {
    this.bausparSumme = bausparSumme;
  }

  public BausparAngebot einmalzahlung(BigDecimal einmalzahlung) {
    this.einmalzahlung = einmalzahlung;
    return this;
  }

   /**
   * Get einmalzahlung
   * @return einmalzahlung
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getEinmalzahlung() {
    return einmalzahlung;
  }

  public void setEinmalzahlung(BigDecimal einmalzahlung) {
    this.einmalzahlung = einmalzahlung;
  }

  public BausparAngebot id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public BausparAngebot produktAnbieter(ProduktAnbieter produktAnbieter) {
    this.produktAnbieter = produktAnbieter;
    return this;
  }

   /**
   * Get produktAnbieter
   * @return produktAnbieter
  **/
  @ApiModelProperty(example = "null", value = "")
  public ProduktAnbieter getProduktAnbieter() {
    return produktAnbieter;
  }

  public void setProduktAnbieter(ProduktAnbieter produktAnbieter) {
    this.produktAnbieter = produktAnbieter;
  }

  public BausparAngebot sparPhase(SparPhase sparPhase) {
    this.sparPhase = sparPhase;
    return this;
  }

   /**
   * Get sparPhase
   * @return sparPhase
  **/
  @ApiModelProperty(example = "null", value = "")
  public SparPhase getSparPhase() {
    return sparPhase;
  }

  public void setSparPhase(SparPhase sparPhase) {
    this.sparPhase = sparPhase;
  }

  public BausparAngebot tarif(String tarif) {
    this.tarif = tarif;
    return this;
  }

   /**
   * Get tarif
   * @return tarif
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTarif() {
    return tarif;
  }

  public void setTarif(String tarif) {
    this.tarif = tarif;
  }

  public BausparAngebot tilgungsPhase(TilgungsPhase tilgungsPhase) {
    this.tilgungsPhase = tilgungsPhase;
    return this;
  }

   /**
   * Get tilgungsPhase
   * @return tilgungsPhase
  **/
  @ApiModelProperty(example = "null", value = "")
  public TilgungsPhase getTilgungsPhase() {
    return tilgungsPhase;
  }

  public void setTilgungsPhase(TilgungsPhase tilgungsPhase) {
    this.tilgungsPhase = tilgungsPhase;
  }

  public BausparAngebot vertragsBeginn(LocalDate vertragsBeginn) {
    this.vertragsBeginn = vertragsBeginn;
    return this;
  }

   /**
   * Get vertragsBeginn
   * @return vertragsBeginn
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDate getVertragsBeginn() {
    return vertragsBeginn;
  }

  public void setVertragsBeginn(LocalDate vertragsBeginn) {
    this.vertragsBeginn = vertragsBeginn;
  }

  public BausparAngebot vertragsNummer(String vertragsNummer) {
    this.vertragsNummer = vertragsNummer;
    return this;
  }

   /**
   * Get vertragsNummer
   * @return vertragsNummer
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVertragsNummer() {
    return vertragsNummer;
  }

  public void setVertragsNummer(String vertragsNummer) {
    this.vertragsNummer = vertragsNummer;
  }

  public BausparAngebot verwaltungsgebuehrenJaehrlich(BigDecimal verwaltungsgebuehrenJaehrlich) {
    this.verwaltungsgebuehrenJaehrlich = verwaltungsgebuehrenJaehrlich;
    return this;
  }

   /**
   * Get verwaltungsgebuehrenJaehrlich
   * @return verwaltungsgebuehrenJaehrlich
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getVerwaltungsgebuehrenJaehrlich() {
    return verwaltungsgebuehrenJaehrlich;
  }

  public void setVerwaltungsgebuehrenJaehrlich(BigDecimal verwaltungsgebuehrenJaehrlich) {
    this.verwaltungsgebuehrenJaehrlich = verwaltungsgebuehrenJaehrlich;
  }

  public BausparAngebot zuteilungsDatum(LocalDate zuteilungsDatum) {
    this.zuteilungsDatum = zuteilungsDatum;
    return this;
  }

   /**
   * Get zuteilungsDatum
   * @return zuteilungsDatum
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDate getZuteilungsDatum() {
    return zuteilungsDatum;
  }

  public void setZuteilungsDatum(LocalDate zuteilungsDatum) {
    this.zuteilungsDatum = zuteilungsDatum;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BausparAngebot bausparAngebot = (BausparAngebot) o;
    return Objects.equals(this.abschlussGebuehr, bausparAngebot.abschlussGebuehr) &&
        Objects.equals(this.angebotsHinweisFuerAntragsteller, bausparAngebot.angebotsHinweisFuerAntragsteller) &&
        Objects.equals(this.bausparSumme, bausparAngebot.bausparSumme) &&
        Objects.equals(this.einmalzahlung, bausparAngebot.einmalzahlung) &&
        Objects.equals(this.id, bausparAngebot.id) &&
        Objects.equals(this.produktAnbieter, bausparAngebot.produktAnbieter) &&
        Objects.equals(this.sparPhase, bausparAngebot.sparPhase) &&
        Objects.equals(this.tarif, bausparAngebot.tarif) &&
        Objects.equals(this.tilgungsPhase, bausparAngebot.tilgungsPhase) &&
        Objects.equals(this.vertragsBeginn, bausparAngebot.vertragsBeginn) &&
        Objects.equals(this.vertragsNummer, bausparAngebot.vertragsNummer) &&
        Objects.equals(this.verwaltungsgebuehrenJaehrlich, bausparAngebot.verwaltungsgebuehrenJaehrlich) &&
        Objects.equals(this.zuteilungsDatum, bausparAngebot.zuteilungsDatum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(abschlussGebuehr, angebotsHinweisFuerAntragsteller, bausparSumme, einmalzahlung, id, produktAnbieter, sparPhase, tarif, tilgungsPhase, vertragsBeginn, vertragsNummer, verwaltungsgebuehrenJaehrlich, zuteilungsDatum);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BausparAngebot {\n");
    
    sb.append("    abschlussGebuehr: ").append(toIndentedString(abschlussGebuehr)).append("\n");
    sb.append("    angebotsHinweisFuerAntragsteller: ").append(toIndentedString(angebotsHinweisFuerAntragsteller)).append("\n");
    sb.append("    bausparSumme: ").append(toIndentedString(bausparSumme)).append("\n");
    sb.append("    einmalzahlung: ").append(toIndentedString(einmalzahlung)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    produktAnbieter: ").append(toIndentedString(produktAnbieter)).append("\n");
    sb.append("    sparPhase: ").append(toIndentedString(sparPhase)).append("\n");
    sb.append("    tarif: ").append(toIndentedString(tarif)).append("\n");
    sb.append("    tilgungsPhase: ").append(toIndentedString(tilgungsPhase)).append("\n");
    sb.append("    vertragsBeginn: ").append(toIndentedString(vertragsBeginn)).append("\n");
    sb.append("    vertragsNummer: ").append(toIndentedString(vertragsNummer)).append("\n");
    sb.append("    verwaltungsgebuehrenJaehrlich: ").append(toIndentedString(verwaltungsgebuehrenJaehrlich)).append("\n");
    sb.append("    zuteilungsDatum: ").append(toIndentedString(zuteilungsDatum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

