/**
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 0.1
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import de.europace.eli.model.ProduktAnbieter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;


/**
 * Beleihung
 */

public class Beleihung   {
  @JsonProperty("auslauf")
  private BigDecimal auslauf = null;

  @JsonProperty("produktanbieter")
  private ProduktAnbieter produktanbieter = null;

  @JsonProperty("summe")
  private BigDecimal summe = null;

  public Beleihung auslauf(BigDecimal auslauf) {
    this.auslauf = auslauf;
    return this;
  }

   /**
   * Get auslauf
   * @return auslauf
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getAuslauf() {
    return auslauf;
  }

  public void setAuslauf(BigDecimal auslauf) {
    this.auslauf = auslauf;
  }

  public Beleihung produktanbieter(ProduktAnbieter produktanbieter) {
    this.produktanbieter = produktanbieter;
    return this;
  }

   /**
   * Get produktanbieter
   * @return produktanbieter
  **/
  @ApiModelProperty(example = "null", value = "")
  public ProduktAnbieter getProduktanbieter() {
    return produktanbieter;
  }

  public void setProduktanbieter(ProduktAnbieter produktanbieter) {
    this.produktanbieter = produktanbieter;
  }

  public Beleihung summe(BigDecimal summe) {
    this.summe = summe;
    return this;
  }

   /**
   * Get summe
   * @return summe
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getSumme() {
    return summe;
  }

  public void setSumme(BigDecimal summe) {
    this.summe = summe;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Beleihung beleihung = (Beleihung) o;
    return Objects.equals(this.auslauf, beleihung.auslauf) &&
        Objects.equals(this.produktanbieter, beleihung.produktanbieter) &&
        Objects.equals(this.summe, beleihung.summe);
  }

  @Override
  public int hashCode() {
    return Objects.hash(auslauf, produktanbieter, summe);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Beleihung {\n");
    
    sb.append("    auslauf: ").append(toIndentedString(auslauf)).append("\n");
    sb.append("    produktanbieter: ").append(toIndentedString(produktanbieter)).append("\n");
    sb.append("    summe: ").append(toIndentedString(summe)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

