/*
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 1.0
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * Bereitstellung
 */

public class Bereitstellung {
  @JsonProperty("bereitstellungsZins")
  private BigDecimal bereitstellungsZins = null;

  @JsonProperty("bereitstellungsZinsfreieZeitInMonaten")
  private Integer bereitstellungsZinsfreieZeitInMonaten = null;

  public Bereitstellung bereitstellungsZins(BigDecimal bereitstellungsZins) {
    this.bereitstellungsZins = bereitstellungsZins;
    return this;
  }

   /**
   * Get bereitstellungsZins
   * @return bereitstellungsZins
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getBereitstellungsZins() {
    return bereitstellungsZins;
  }

  public void setBereitstellungsZins(BigDecimal bereitstellungsZins) {
    this.bereitstellungsZins = bereitstellungsZins;
  }

  public Bereitstellung bereitstellungsZinsfreieZeitInMonaten(Integer bereitstellungsZinsfreieZeitInMonaten) {
    this.bereitstellungsZinsfreieZeitInMonaten = bereitstellungsZinsfreieZeitInMonaten;
    return this;
  }

   /**
   * Get bereitstellungsZinsfreieZeitInMonaten
   * @return bereitstellungsZinsfreieZeitInMonaten
  **/
  @ApiModelProperty(value = "")
  public Integer getBereitstellungsZinsfreieZeitInMonaten() {
    return bereitstellungsZinsfreieZeitInMonaten;
  }

  public void setBereitstellungsZinsfreieZeitInMonaten(Integer bereitstellungsZinsfreieZeitInMonaten) {
    this.bereitstellungsZinsfreieZeitInMonaten = bereitstellungsZinsfreieZeitInMonaten;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Bereitstellung bereitstellung = (Bereitstellung) o;
    return Objects.equals(this.bereitstellungsZins, bereitstellung.bereitstellungsZins) &&
        Objects.equals(this.bereitstellungsZinsfreieZeitInMonaten, bereitstellung.bereitstellungsZinsfreieZeitInMonaten);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bereitstellungsZins, bereitstellungsZinsfreieZeitInMonaten);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Bereitstellung {\n");
    
    sb.append("    bereitstellungsZins: ").append(toIndentedString(bereitstellungsZins)).append("\n");
    sb.append("    bereitstellungsZinsfreieZeitInMonaten: ").append(toIndentedString(bereitstellungsZinsfreieZeitInMonaten)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

