/*
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 0.1
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * BereitstellungsZinsFreieZeitPraeferenz
 */

public class BereitstellungsZinsFreieZeitPraeferenz {
  @JsonProperty("darlehenBenoetigtInMonaten")
  private Integer darlehenBenoetigtInMonaten = null;

  @JsonProperty("praeferenzAuswahl")
  private String praeferenzAuswahl = null;

  @JsonProperty("zusatzlicheKommentare")
  private String zusatzlicheKommentare = null;

  public BereitstellungsZinsFreieZeitPraeferenz darlehenBenoetigtInMonaten(Integer darlehenBenoetigtInMonaten) {
    this.darlehenBenoetigtInMonaten = darlehenBenoetigtInMonaten;
    return this;
  }

   /**
   * wenn praeferenzAuswahl==IN_MONATEN
   * @return darlehenBenoetigtInMonaten
  **/
  @ApiModelProperty(example = "null", value = "wenn praeferenzAuswahl==IN_MONATEN")
  public Integer getDarlehenBenoetigtInMonaten() {
    return darlehenBenoetigtInMonaten;
  }

  public void setDarlehenBenoetigtInMonaten(Integer darlehenBenoetigtInMonaten) {
    this.darlehenBenoetigtInMonaten = darlehenBenoetigtInMonaten;
  }

  public BereitstellungsZinsFreieZeitPraeferenz praeferenzAuswahl(String praeferenzAuswahl) {
    this.praeferenzAuswahl = praeferenzAuswahl;
    return this;
  }

   /**
   * Erlaubt sind: MIT_DER_ERSTEN_AUSZAHLUNG,IN_MONATEN,NOCH_NICHT_FESTGELEGT,EGAL. Neue Ausprägungen können kurzfristig hinzukommen. Der Client muss daher mit unbekannten Werten umgehen können.
   * @return praeferenzAuswahl
  **/
  @ApiModelProperty(example = "null", value = "Erlaubt sind: MIT_DER_ERSTEN_AUSZAHLUNG,IN_MONATEN,NOCH_NICHT_FESTGELEGT,EGAL. Neue Ausprägungen können kurzfristig hinzukommen. Der Client muss daher mit unbekannten Werten umgehen können.")
  public String getPraeferenzAuswahl() {
    return praeferenzAuswahl;
  }

  public void setPraeferenzAuswahl(String praeferenzAuswahl) {
    this.praeferenzAuswahl = praeferenzAuswahl;
  }

  public BereitstellungsZinsFreieZeitPraeferenz zusatzlicheKommentare(String zusatzlicheKommentare) {
    this.zusatzlicheKommentare = zusatzlicheKommentare;
    return this;
  }

   /**
   * Get zusatzlicheKommentare
   * @return zusatzlicheKommentare
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getZusatzlicheKommentare() {
    return zusatzlicheKommentare;
  }

  public void setZusatzlicheKommentare(String zusatzlicheKommentare) {
    this.zusatzlicheKommentare = zusatzlicheKommentare;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BereitstellungsZinsFreieZeitPraeferenz bereitstellungsZinsFreieZeitPraeferenz = (BereitstellungsZinsFreieZeitPraeferenz) o;
    return Objects.equals(this.darlehenBenoetigtInMonaten, bereitstellungsZinsFreieZeitPraeferenz.darlehenBenoetigtInMonaten) &&
        Objects.equals(this.praeferenzAuswahl, bereitstellungsZinsFreieZeitPraeferenz.praeferenzAuswahl) &&
        Objects.equals(this.zusatzlicheKommentare, bereitstellungsZinsFreieZeitPraeferenz.zusatzlicheKommentare);
  }

  @Override
  public int hashCode() {
    return Objects.hash(darlehenBenoetigtInMonaten, praeferenzAuswahl, zusatzlicheKommentare);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BereitstellungsZinsFreieZeitPraeferenz {\n");
    
    sb.append("    darlehenBenoetigtInMonaten: ").append(toIndentedString(darlehenBenoetigtInMonaten)).append("\n");
    sb.append("    praeferenzAuswahl: ").append(toIndentedString(praeferenzAuswahl)).append("\n");
    sb.append("    zusatzlicheKommentare: ").append(toIndentedString(zusatzlicheKommentare)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

