/*
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 1.0
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import de.europace.eli.model.ProduktAnbieter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * BestehenderBausparvertrag
 */

public class BestehenderBausparvertrag {
  @JsonProperty("abschlussGebuehr")
  private BigDecimal abschlussGebuehr = null;

  @JsonProperty("aktuellerWert")
  private BigDecimal aktuellerWert = null;

  @JsonProperty("bausparSumme")
  private BigDecimal bausparSumme = null;

  @JsonProperty("einmalzahlung")
  private BigDecimal einmalzahlung = null;

  @JsonProperty("ertrag")
  private BigDecimal ertrag = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("maximalAufzuloesenderBetrag")
  private BigDecimal maximalAufzuloesenderBetrag = null;

  @JsonProperty("produktAnbieter")
  private ProduktAnbieter produktAnbieter = null;

  @JsonProperty("sparBeitragMonatlich")
  private BigDecimal sparBeitragMonatlich = null;

  @JsonProperty("tarif")
  private String tarif = null;

  /**
   * Gets or Sets vermoegensEinsatz
   */
  public enum VermoegensEinsatzEnum {
    KEIN_EINSATZ("KEIN_EINSATZ"),
    
    ABTRETEN("ABTRETEN"),
    
    AUFLOESEN("AUFLOESEN");

    private String value;

    VermoegensEinsatzEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static VermoegensEinsatzEnum fromValue(String text) {
      for (VermoegensEinsatzEnum b : VermoegensEinsatzEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("vermoegensEinsatz")
  private VermoegensEinsatzEnum vermoegensEinsatz = null;

  @JsonProperty("vertragsBeginn")
  private LocalDate vertragsBeginn = null;

  @JsonProperty("vertragsNummer")
  private String vertragsNummer = null;

  @JsonProperty("verwaltungsgebuehrenJaehrlich")
  private BigDecimal verwaltungsgebuehrenJaehrlich = null;

  @JsonProperty("zukuenftigeEinnahmen")
  private BigDecimal zukuenftigeEinnahmen = null;

  @JsonProperty("zuteilungsDatum")
  private LocalDate zuteilungsDatum = null;

  public BestehenderBausparvertrag abschlussGebuehr(BigDecimal abschlussGebuehr) {
    this.abschlussGebuehr = abschlussGebuehr;
    return this;
  }

   /**
   * Get abschlussGebuehr
   * @return abschlussGebuehr
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getAbschlussGebuehr() {
    return abschlussGebuehr;
  }

  public void setAbschlussGebuehr(BigDecimal abschlussGebuehr) {
    this.abschlussGebuehr = abschlussGebuehr;
  }

  public BestehenderBausparvertrag aktuellerWert(BigDecimal aktuellerWert) {
    this.aktuellerWert = aktuellerWert;
    return this;
  }

   /**
   * Get aktuellerWert
   * @return aktuellerWert
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getAktuellerWert() {
    return aktuellerWert;
  }

  public void setAktuellerWert(BigDecimal aktuellerWert) {
    this.aktuellerWert = aktuellerWert;
  }

  public BestehenderBausparvertrag bausparSumme(BigDecimal bausparSumme) {
    this.bausparSumme = bausparSumme;
    return this;
  }

   /**
   * Get bausparSumme
   * @return bausparSumme
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getBausparSumme() {
    return bausparSumme;
  }

  public void setBausparSumme(BigDecimal bausparSumme) {
    this.bausparSumme = bausparSumme;
  }

  public BestehenderBausparvertrag einmalzahlung(BigDecimal einmalzahlung) {
    this.einmalzahlung = einmalzahlung;
    return this;
  }

   /**
   * Get einmalzahlung
   * @return einmalzahlung
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getEinmalzahlung() {
    return einmalzahlung;
  }

  public void setEinmalzahlung(BigDecimal einmalzahlung) {
    this.einmalzahlung = einmalzahlung;
  }

  public BestehenderBausparvertrag ertrag(BigDecimal ertrag) {
    this.ertrag = ertrag;
    return this;
  }

   /**
   * Get ertrag
   * @return ertrag
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getErtrag() {
    return ertrag;
  }

  public void setErtrag(BigDecimal ertrag) {
    this.ertrag = ertrag;
  }

  public BestehenderBausparvertrag id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Zur Referenzierung an anderer Stelle notwendig. Wenn nicht angegeben, dann wird dieses Feld automatisch befüllt.
   * @return id
  **/
  @ApiModelProperty(value = "Zur Referenzierung an anderer Stelle notwendig. Wenn nicht angegeben, dann wird dieses Feld automatisch befüllt.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public BestehenderBausparvertrag maximalAufzuloesenderBetrag(BigDecimal maximalAufzuloesenderBetrag) {
    this.maximalAufzuloesenderBetrag = maximalAufzuloesenderBetrag;
    return this;
  }

   /**
   * Get maximalAufzuloesenderBetrag
   * @return maximalAufzuloesenderBetrag
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getMaximalAufzuloesenderBetrag() {
    return maximalAufzuloesenderBetrag;
  }

  public void setMaximalAufzuloesenderBetrag(BigDecimal maximalAufzuloesenderBetrag) {
    this.maximalAufzuloesenderBetrag = maximalAufzuloesenderBetrag;
  }

  public BestehenderBausparvertrag produktAnbieter(ProduktAnbieter produktAnbieter) {
    this.produktAnbieter = produktAnbieter;
    return this;
  }

   /**
   * Get produktAnbieter
   * @return produktAnbieter
  **/
  @ApiModelProperty(value = "")
  public ProduktAnbieter getProduktAnbieter() {
    return produktAnbieter;
  }

  public void setProduktAnbieter(ProduktAnbieter produktAnbieter) {
    this.produktAnbieter = produktAnbieter;
  }

  public BestehenderBausparvertrag sparBeitragMonatlich(BigDecimal sparBeitragMonatlich) {
    this.sparBeitragMonatlich = sparBeitragMonatlich;
    return this;
  }

   /**
   * Get sparBeitragMonatlich
   * @return sparBeitragMonatlich
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getSparBeitragMonatlich() {
    return sparBeitragMonatlich;
  }

  public void setSparBeitragMonatlich(BigDecimal sparBeitragMonatlich) {
    this.sparBeitragMonatlich = sparBeitragMonatlich;
  }

  public BestehenderBausparvertrag tarif(String tarif) {
    this.tarif = tarif;
    return this;
  }

   /**
   * Get tarif
   * @return tarif
  **/
  @ApiModelProperty(value = "")
  public String getTarif() {
    return tarif;
  }

  public void setTarif(String tarif) {
    this.tarif = tarif;
  }

  public BestehenderBausparvertrag vermoegensEinsatz(VermoegensEinsatzEnum vermoegensEinsatz) {
    this.vermoegensEinsatz = vermoegensEinsatz;
    return this;
  }

   /**
   * Get vermoegensEinsatz
   * @return vermoegensEinsatz
  **/
  @ApiModelProperty(value = "")
  public VermoegensEinsatzEnum getVermoegensEinsatz() {
    return vermoegensEinsatz;
  }

  public void setVermoegensEinsatz(VermoegensEinsatzEnum vermoegensEinsatz) {
    this.vermoegensEinsatz = vermoegensEinsatz;
  }

  public BestehenderBausparvertrag vertragsBeginn(LocalDate vertragsBeginn) {
    this.vertragsBeginn = vertragsBeginn;
    return this;
  }

   /**
   * Get vertragsBeginn
   * @return vertragsBeginn
  **/
  @ApiModelProperty(value = "")
  public LocalDate getVertragsBeginn() {
    return vertragsBeginn;
  }

  public void setVertragsBeginn(LocalDate vertragsBeginn) {
    this.vertragsBeginn = vertragsBeginn;
  }

  public BestehenderBausparvertrag vertragsNummer(String vertragsNummer) {
    this.vertragsNummer = vertragsNummer;
    return this;
  }

   /**
   * Get vertragsNummer
   * @return vertragsNummer
  **/
  @ApiModelProperty(value = "")
  public String getVertragsNummer() {
    return vertragsNummer;
  }

  public void setVertragsNummer(String vertragsNummer) {
    this.vertragsNummer = vertragsNummer;
  }

  public BestehenderBausparvertrag verwaltungsgebuehrenJaehrlich(BigDecimal verwaltungsgebuehrenJaehrlich) {
    this.verwaltungsgebuehrenJaehrlich = verwaltungsgebuehrenJaehrlich;
    return this;
  }

   /**
   * Get verwaltungsgebuehrenJaehrlich
   * @return verwaltungsgebuehrenJaehrlich
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getVerwaltungsgebuehrenJaehrlich() {
    return verwaltungsgebuehrenJaehrlich;
  }

  public void setVerwaltungsgebuehrenJaehrlich(BigDecimal verwaltungsgebuehrenJaehrlich) {
    this.verwaltungsgebuehrenJaehrlich = verwaltungsgebuehrenJaehrlich;
  }

  public BestehenderBausparvertrag zukuenftigeEinnahmen(BigDecimal zukuenftigeEinnahmen) {
    this.zukuenftigeEinnahmen = zukuenftigeEinnahmen;
    return this;
  }

   /**
   * Get zukuenftigeEinnahmen
   * @return zukuenftigeEinnahmen
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getZukuenftigeEinnahmen() {
    return zukuenftigeEinnahmen;
  }

  public void setZukuenftigeEinnahmen(BigDecimal zukuenftigeEinnahmen) {
    this.zukuenftigeEinnahmen = zukuenftigeEinnahmen;
  }

  public BestehenderBausparvertrag zuteilungsDatum(LocalDate zuteilungsDatum) {
    this.zuteilungsDatum = zuteilungsDatum;
    return this;
  }

   /**
   * Get zuteilungsDatum
   * @return zuteilungsDatum
  **/
  @ApiModelProperty(value = "")
  public LocalDate getZuteilungsDatum() {
    return zuteilungsDatum;
  }

  public void setZuteilungsDatum(LocalDate zuteilungsDatum) {
    this.zuteilungsDatum = zuteilungsDatum;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BestehenderBausparvertrag bestehenderBausparvertrag = (BestehenderBausparvertrag) o;
    return Objects.equals(this.abschlussGebuehr, bestehenderBausparvertrag.abschlussGebuehr) &&
        Objects.equals(this.aktuellerWert, bestehenderBausparvertrag.aktuellerWert) &&
        Objects.equals(this.bausparSumme, bestehenderBausparvertrag.bausparSumme) &&
        Objects.equals(this.einmalzahlung, bestehenderBausparvertrag.einmalzahlung) &&
        Objects.equals(this.ertrag, bestehenderBausparvertrag.ertrag) &&
        Objects.equals(this.id, bestehenderBausparvertrag.id) &&
        Objects.equals(this.maximalAufzuloesenderBetrag, bestehenderBausparvertrag.maximalAufzuloesenderBetrag) &&
        Objects.equals(this.produktAnbieter, bestehenderBausparvertrag.produktAnbieter) &&
        Objects.equals(this.sparBeitragMonatlich, bestehenderBausparvertrag.sparBeitragMonatlich) &&
        Objects.equals(this.tarif, bestehenderBausparvertrag.tarif) &&
        Objects.equals(this.vermoegensEinsatz, bestehenderBausparvertrag.vermoegensEinsatz) &&
        Objects.equals(this.vertragsBeginn, bestehenderBausparvertrag.vertragsBeginn) &&
        Objects.equals(this.vertragsNummer, bestehenderBausparvertrag.vertragsNummer) &&
        Objects.equals(this.verwaltungsgebuehrenJaehrlich, bestehenderBausparvertrag.verwaltungsgebuehrenJaehrlich) &&
        Objects.equals(this.zukuenftigeEinnahmen, bestehenderBausparvertrag.zukuenftigeEinnahmen) &&
        Objects.equals(this.zuteilungsDatum, bestehenderBausparvertrag.zuteilungsDatum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(abschlussGebuehr, aktuellerWert, bausparSumme, einmalzahlung, ertrag, id, maximalAufzuloesenderBetrag, produktAnbieter, sparBeitragMonatlich, tarif, vermoegensEinsatz, vertragsBeginn, vertragsNummer, verwaltungsgebuehrenJaehrlich, zukuenftigeEinnahmen, zuteilungsDatum);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BestehenderBausparvertrag {\n");
    
    sb.append("    abschlussGebuehr: ").append(toIndentedString(abschlussGebuehr)).append("\n");
    sb.append("    aktuellerWert: ").append(toIndentedString(aktuellerWert)).append("\n");
    sb.append("    bausparSumme: ").append(toIndentedString(bausparSumme)).append("\n");
    sb.append("    einmalzahlung: ").append(toIndentedString(einmalzahlung)).append("\n");
    sb.append("    ertrag: ").append(toIndentedString(ertrag)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    maximalAufzuloesenderBetrag: ").append(toIndentedString(maximalAufzuloesenderBetrag)).append("\n");
    sb.append("    produktAnbieter: ").append(toIndentedString(produktAnbieter)).append("\n");
    sb.append("    sparBeitragMonatlich: ").append(toIndentedString(sparBeitragMonatlich)).append("\n");
    sb.append("    tarif: ").append(toIndentedString(tarif)).append("\n");
    sb.append("    vermoegensEinsatz: ").append(toIndentedString(vermoegensEinsatz)).append("\n");
    sb.append("    vertragsBeginn: ").append(toIndentedString(vertragsBeginn)).append("\n");
    sb.append("    vertragsNummer: ").append(toIndentedString(vertragsNummer)).append("\n");
    sb.append("    verwaltungsgebuehrenJaehrlich: ").append(toIndentedString(verwaltungsgebuehrenJaehrlich)).append("\n");
    sb.append("    zukuenftigeEinnahmen: ").append(toIndentedString(zukuenftigeEinnahmen)).append("\n");
    sb.append("    zuteilungsDatum: ").append(toIndentedString(zuteilungsDatum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

