/*
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 0.1
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * BestehenderBausparvertrag
 */

public class BestehenderBausparvertrag {
  @JsonProperty("aktuellerWert")
  private BigDecimal aktuellerWert = null;

  @JsonProperty("ertrag")
  private BigDecimal ertrag = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("maximalAufzuloesenderBetrag")
  private BigDecimal maximalAufzuloesenderBetrag = null;

  @JsonProperty("sparBeitragMonatlich")
  private BigDecimal sparBeitragMonatlich = null;

  /**
   * Gets or Sets vermoegensEinsatz
   */
  public enum VermoegensEinsatzEnum {
    KEIN_EINSATZ("KEIN_EINSATZ"),
    
    ABTRETEN("ABTRETEN"),
    
    AUFLOESEN("AUFLOESEN");

    private String value;

    VermoegensEinsatzEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static VermoegensEinsatzEnum fromValue(String text) {
      for (VermoegensEinsatzEnum b : VermoegensEinsatzEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("vermoegensEinsatz")
  private VermoegensEinsatzEnum vermoegensEinsatz = null;

  @JsonProperty("zukuenftigeEinnahmen")
  private BigDecimal zukuenftigeEinnahmen = null;

  public BestehenderBausparvertrag aktuellerWert(BigDecimal aktuellerWert) {
    this.aktuellerWert = aktuellerWert;
    return this;
  }

   /**
   * Get aktuellerWert
   * @return aktuellerWert
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getAktuellerWert() {
    return aktuellerWert;
  }

  public void setAktuellerWert(BigDecimal aktuellerWert) {
    this.aktuellerWert = aktuellerWert;
  }

  public BestehenderBausparvertrag ertrag(BigDecimal ertrag) {
    this.ertrag = ertrag;
    return this;
  }

   /**
   * Get ertrag
   * @return ertrag
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getErtrag() {
    return ertrag;
  }

  public void setErtrag(BigDecimal ertrag) {
    this.ertrag = ertrag;
  }

  public BestehenderBausparvertrag id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public BestehenderBausparvertrag maximalAufzuloesenderBetrag(BigDecimal maximalAufzuloesenderBetrag) {
    this.maximalAufzuloesenderBetrag = maximalAufzuloesenderBetrag;
    return this;
  }

   /**
   * Get maximalAufzuloesenderBetrag
   * @return maximalAufzuloesenderBetrag
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getMaximalAufzuloesenderBetrag() {
    return maximalAufzuloesenderBetrag;
  }

  public void setMaximalAufzuloesenderBetrag(BigDecimal maximalAufzuloesenderBetrag) {
    this.maximalAufzuloesenderBetrag = maximalAufzuloesenderBetrag;
  }

  public BestehenderBausparvertrag sparBeitragMonatlich(BigDecimal sparBeitragMonatlich) {
    this.sparBeitragMonatlich = sparBeitragMonatlich;
    return this;
  }

   /**
   * Get sparBeitragMonatlich
   * @return sparBeitragMonatlich
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getSparBeitragMonatlich() {
    return sparBeitragMonatlich;
  }

  public void setSparBeitragMonatlich(BigDecimal sparBeitragMonatlich) {
    this.sparBeitragMonatlich = sparBeitragMonatlich;
  }

  public BestehenderBausparvertrag vermoegensEinsatz(VermoegensEinsatzEnum vermoegensEinsatz) {
    this.vermoegensEinsatz = vermoegensEinsatz;
    return this;
  }

   /**
   * Get vermoegensEinsatz
   * @return vermoegensEinsatz
  **/
  @ApiModelProperty(example = "null", value = "")
  public VermoegensEinsatzEnum getVermoegensEinsatz() {
    return vermoegensEinsatz;
  }

  public void setVermoegensEinsatz(VermoegensEinsatzEnum vermoegensEinsatz) {
    this.vermoegensEinsatz = vermoegensEinsatz;
  }

  public BestehenderBausparvertrag zukuenftigeEinnahmen(BigDecimal zukuenftigeEinnahmen) {
    this.zukuenftigeEinnahmen = zukuenftigeEinnahmen;
    return this;
  }

   /**
   * Get zukuenftigeEinnahmen
   * @return zukuenftigeEinnahmen
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getZukuenftigeEinnahmen() {
    return zukuenftigeEinnahmen;
  }

  public void setZukuenftigeEinnahmen(BigDecimal zukuenftigeEinnahmen) {
    this.zukuenftigeEinnahmen = zukuenftigeEinnahmen;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BestehenderBausparvertrag bestehenderBausparvertrag = (BestehenderBausparvertrag) o;
    return Objects.equals(this.aktuellerWert, bestehenderBausparvertrag.aktuellerWert) &&
        Objects.equals(this.ertrag, bestehenderBausparvertrag.ertrag) &&
        Objects.equals(this.id, bestehenderBausparvertrag.id) &&
        Objects.equals(this.maximalAufzuloesenderBetrag, bestehenderBausparvertrag.maximalAufzuloesenderBetrag) &&
        Objects.equals(this.sparBeitragMonatlich, bestehenderBausparvertrag.sparBeitragMonatlich) &&
        Objects.equals(this.vermoegensEinsatz, bestehenderBausparvertrag.vermoegensEinsatz) &&
        Objects.equals(this.zukuenftigeEinnahmen, bestehenderBausparvertrag.zukuenftigeEinnahmen);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aktuellerWert, ertrag, id, maximalAufzuloesenderBetrag, sparBeitragMonatlich, vermoegensEinsatz, zukuenftigeEinnahmen);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BestehenderBausparvertrag {\n");
    
    sb.append("    aktuellerWert: ").append(toIndentedString(aktuellerWert)).append("\n");
    sb.append("    ertrag: ").append(toIndentedString(ertrag)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    maximalAufzuloesenderBetrag: ").append(toIndentedString(maximalAufzuloesenderBetrag)).append("\n");
    sb.append("    sparBeitragMonatlich: ").append(toIndentedString(sparBeitragMonatlich)).append("\n");
    sb.append("    vermoegensEinsatz: ").append(toIndentedString(vermoegensEinsatz)).append("\n");
    sb.append("    zukuenftigeEinnahmen: ").append(toIndentedString(zukuenftigeEinnahmen)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

