/*
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 0.1
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import de.europace.eli.model.ProduktAnbieter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.joda.time.LocalDate;

/**
 * BestehendesDarlehenDesFinanzierungsObjekts
 */

public class BestehendesDarlehenDesFinanzierungsObjekts {
  @JsonProperty("abzuloesendeRestschuld")
  private BigDecimal abzuloesendeRestschuld = null;

  @JsonProperty("aktuelleRestschuldWennNichtAbzuloesen")
  private BigDecimal aktuelleRestschuldWennNichtAbzuloesen = null;

  @JsonProperty("darlehensArt")
  private String darlehensArt = null;

  @JsonProperty("darlehensGeber")
  private ProduktAnbieter darlehensGeber = null;

  @JsonProperty("eingetrageneGrundschuld")
  private BigDecimal eingetrageneGrundschuld = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("rateMonatlich")
  private BigDecimal rateMonatlich = null;

  /**
   * Beschreibt wie das Darlehen im Zusammenhang mit dem Vorhaben, behandelt werden soll.
   */
  public enum VerwendenAlsEnum {
    ABLOESEN("ABLOESEN"),
    
    TRITT_IM_RANG_ZURUECK("TRITT_IM_RANG_ZURUECK"),
    
    TRITT_NICHT_IM_RANG_ZURUECK("TRITT_NICHT_IM_RANG_ZURUECK");

    private String value;

    VerwendenAlsEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static VerwendenAlsEnum fromValue(String text) {
      for (VerwendenAlsEnum b : VerwendenAlsEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("verwendenAls")
  private VerwendenAlsEnum verwendenAls = null;

  @JsonProperty("zinsBindungEndetAm")
  private LocalDate zinsBindungEndetAm = null;

  public BestehendesDarlehenDesFinanzierungsObjekts abzuloesendeRestschuld(BigDecimal abzuloesendeRestschuld) {
    this.abzuloesendeRestschuld = abzuloesendeRestschuld;
    return this;
  }

   /**
   * Get abzuloesendeRestschuld
   * @return abzuloesendeRestschuld
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getAbzuloesendeRestschuld() {
    return abzuloesendeRestschuld;
  }

  public void setAbzuloesendeRestschuld(BigDecimal abzuloesendeRestschuld) {
    this.abzuloesendeRestschuld = abzuloesendeRestschuld;
  }

  public BestehendesDarlehenDesFinanzierungsObjekts aktuelleRestschuldWennNichtAbzuloesen(BigDecimal aktuelleRestschuldWennNichtAbzuloesen) {
    this.aktuelleRestschuldWennNichtAbzuloesen = aktuelleRestschuldWennNichtAbzuloesen;
    return this;
  }

   /**
   * nur wenn wirdAbgeloest==true
   * @return aktuelleRestschuldWennNichtAbzuloesen
  **/
  @ApiModelProperty(example = "null", value = "nur wenn wirdAbgeloest==true")
  public BigDecimal getAktuelleRestschuldWennNichtAbzuloesen() {
    return aktuelleRestschuldWennNichtAbzuloesen;
  }

  public void setAktuelleRestschuldWennNichtAbzuloesen(BigDecimal aktuelleRestschuldWennNichtAbzuloesen) {
    this.aktuelleRestschuldWennNichtAbzuloesen = aktuelleRestschuldWennNichtAbzuloesen;
  }

  public BestehendesDarlehenDesFinanzierungsObjekts darlehensArt(String darlehensArt) {
    this.darlehensArt = darlehensArt;
    return this;
  }

   /**
   * Erlaubte Werte sind: BAUSPARDARLEHEN,FOERDERDARLEHEN,IMMOBILIENDARLEHEN,SONSTIGES_DARLEHEN. Neue Ausprägungen können kurzfristig hinzukommen. Der Client muss daher mit unbekannten Werten umgehen können.
   * @return darlehensArt
  **/
  @ApiModelProperty(example = "null", value = "Erlaubte Werte sind: BAUSPARDARLEHEN,FOERDERDARLEHEN,IMMOBILIENDARLEHEN,SONSTIGES_DARLEHEN. Neue Ausprägungen können kurzfristig hinzukommen. Der Client muss daher mit unbekannten Werten umgehen können.")
  public String getDarlehensArt() {
    return darlehensArt;
  }

  public void setDarlehensArt(String darlehensArt) {
    this.darlehensArt = darlehensArt;
  }

  public BestehendesDarlehenDesFinanzierungsObjekts darlehensGeber(ProduktAnbieter darlehensGeber) {
    this.darlehensGeber = darlehensGeber;
    return this;
  }

   /**
   * Get darlehensGeber
   * @return darlehensGeber
  **/
  @ApiModelProperty(example = "null", value = "")
  public ProduktAnbieter getDarlehensGeber() {
    return darlehensGeber;
  }

  public void setDarlehensGeber(ProduktAnbieter darlehensGeber) {
    this.darlehensGeber = darlehensGeber;
  }

  public BestehendesDarlehenDesFinanzierungsObjekts eingetrageneGrundschuld(BigDecimal eingetrageneGrundschuld) {
    this.eingetrageneGrundschuld = eingetrageneGrundschuld;
    return this;
  }

   /**
   * Get eingetrageneGrundschuld
   * @return eingetrageneGrundschuld
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getEingetrageneGrundschuld() {
    return eingetrageneGrundschuld;
  }

  public void setEingetrageneGrundschuld(BigDecimal eingetrageneGrundschuld) {
    this.eingetrageneGrundschuld = eingetrageneGrundschuld;
  }

  public BestehendesDarlehenDesFinanzierungsObjekts id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public BestehendesDarlehenDesFinanzierungsObjekts rateMonatlich(BigDecimal rateMonatlich) {
    this.rateMonatlich = rateMonatlich;
    return this;
  }

   /**
   * Get rateMonatlich
   * @return rateMonatlich
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getRateMonatlich() {
    return rateMonatlich;
  }

  public void setRateMonatlich(BigDecimal rateMonatlich) {
    this.rateMonatlich = rateMonatlich;
  }

  public BestehendesDarlehenDesFinanzierungsObjekts verwendenAls(VerwendenAlsEnum verwendenAls) {
    this.verwendenAls = verwendenAls;
    return this;
  }

   /**
   * Beschreibt wie das Darlehen im Zusammenhang mit dem Vorhaben, behandelt werden soll.
   * @return verwendenAls
  **/
  @ApiModelProperty(example = "null", value = "Beschreibt wie das Darlehen im Zusammenhang mit dem Vorhaben, behandelt werden soll.")
  public VerwendenAlsEnum getVerwendenAls() {
    return verwendenAls;
  }

  public void setVerwendenAls(VerwendenAlsEnum verwendenAls) {
    this.verwendenAls = verwendenAls;
  }

  public BestehendesDarlehenDesFinanzierungsObjekts zinsBindungEndetAm(LocalDate zinsBindungEndetAm) {
    this.zinsBindungEndetAm = zinsBindungEndetAm;
    return this;
  }

   /**
   * Get zinsBindungEndetAm
   * @return zinsBindungEndetAm
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDate getZinsBindungEndetAm() {
    return zinsBindungEndetAm;
  }

  public void setZinsBindungEndetAm(LocalDate zinsBindungEndetAm) {
    this.zinsBindungEndetAm = zinsBindungEndetAm;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BestehendesDarlehenDesFinanzierungsObjekts bestehendesDarlehenDesFinanzierungsObjekts = (BestehendesDarlehenDesFinanzierungsObjekts) o;
    return Objects.equals(this.abzuloesendeRestschuld, bestehendesDarlehenDesFinanzierungsObjekts.abzuloesendeRestschuld) &&
        Objects.equals(this.aktuelleRestschuldWennNichtAbzuloesen, bestehendesDarlehenDesFinanzierungsObjekts.aktuelleRestschuldWennNichtAbzuloesen) &&
        Objects.equals(this.darlehensArt, bestehendesDarlehenDesFinanzierungsObjekts.darlehensArt) &&
        Objects.equals(this.darlehensGeber, bestehendesDarlehenDesFinanzierungsObjekts.darlehensGeber) &&
        Objects.equals(this.eingetrageneGrundschuld, bestehendesDarlehenDesFinanzierungsObjekts.eingetrageneGrundschuld) &&
        Objects.equals(this.id, bestehendesDarlehenDesFinanzierungsObjekts.id) &&
        Objects.equals(this.rateMonatlich, bestehendesDarlehenDesFinanzierungsObjekts.rateMonatlich) &&
        Objects.equals(this.verwendenAls, bestehendesDarlehenDesFinanzierungsObjekts.verwendenAls) &&
        Objects.equals(this.zinsBindungEndetAm, bestehendesDarlehenDesFinanzierungsObjekts.zinsBindungEndetAm);
  }

  @Override
  public int hashCode() {
    return Objects.hash(abzuloesendeRestschuld, aktuelleRestschuldWennNichtAbzuloesen, darlehensArt, darlehensGeber, eingetrageneGrundschuld, id, rateMonatlich, verwendenAls, zinsBindungEndetAm);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BestehendesDarlehenDesFinanzierungsObjekts {\n");
    
    sb.append("    abzuloesendeRestschuld: ").append(toIndentedString(abzuloesendeRestschuld)).append("\n");
    sb.append("    aktuelleRestschuldWennNichtAbzuloesen: ").append(toIndentedString(aktuelleRestschuldWennNichtAbzuloesen)).append("\n");
    sb.append("    darlehensArt: ").append(toIndentedString(darlehensArt)).append("\n");
    sb.append("    darlehensGeber: ").append(toIndentedString(darlehensGeber)).append("\n");
    sb.append("    eingetrageneGrundschuld: ").append(toIndentedString(eingetrageneGrundschuld)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rateMonatlich: ").append(toIndentedString(rateMonatlich)).append("\n");
    sb.append("    verwendenAls: ").append(toIndentedString(verwendenAls)).append("\n");
    sb.append("    zinsBindungEndetAm: ").append(toIndentedString(zinsBindungEndetAm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

