/**
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 0.1
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.joda.time.LocalDate;


/**
 * EinkuenfteAusNebentaetigkeit
 */

public class EinkuenfteAusNebentaetigkeit   {
  @JsonProperty("beginnDerNebentaetigkeit")
  private LocalDate beginnDerNebentaetigkeit = null;

  @JsonProperty("einnahmenMonatlich")
  private BigDecimal einnahmenMonatlich = null;

  public EinkuenfteAusNebentaetigkeit beginnDerNebentaetigkeit(LocalDate beginnDerNebentaetigkeit) {
    this.beginnDerNebentaetigkeit = beginnDerNebentaetigkeit;
    return this;
  }

   /**
   * Get beginnDerNebentaetigkeit
   * @return beginnDerNebentaetigkeit
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDate getBeginnDerNebentaetigkeit() {
    return beginnDerNebentaetigkeit;
  }

  public void setBeginnDerNebentaetigkeit(LocalDate beginnDerNebentaetigkeit) {
    this.beginnDerNebentaetigkeit = beginnDerNebentaetigkeit;
  }

  public EinkuenfteAusNebentaetigkeit einnahmenMonatlich(BigDecimal einnahmenMonatlich) {
    this.einnahmenMonatlich = einnahmenMonatlich;
    return this;
  }

   /**
   * Get einnahmenMonatlich
   * @return einnahmenMonatlich
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getEinnahmenMonatlich() {
    return einnahmenMonatlich;
  }

  public void setEinnahmenMonatlich(BigDecimal einnahmenMonatlich) {
    this.einnahmenMonatlich = einnahmenMonatlich;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EinkuenfteAusNebentaetigkeit einkuenfteAusNebentaetigkeit = (EinkuenfteAusNebentaetigkeit) o;
    return Objects.equals(this.beginnDerNebentaetigkeit, einkuenfteAusNebentaetigkeit.beginnDerNebentaetigkeit) &&
        Objects.equals(this.einnahmenMonatlich, einkuenfteAusNebentaetigkeit.einnahmenMonatlich);
  }

  @Override
  public int hashCode() {
    return Objects.hash(beginnDerNebentaetigkeit, einnahmenMonatlich);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EinkuenfteAusNebentaetigkeit {\n");
    
    sb.append("    beginnDerNebentaetigkeit: ").append(toIndentedString(beginnDerNebentaetigkeit)).append("\n");
    sb.append("    einnahmenMonatlich: ").append(toIndentedString(einnahmenMonatlich)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

