/*
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 1.0
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import de.europace.eli.model.FinanzierungsVorschlag;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ErgebnisListeResource
 */

public class ErgebnisListeResource {
  @JsonProperty("finanzierungsVorschlaege")
  private List<FinanzierungsVorschlag> finanzierungsVorschlaege = null;

  public ErgebnisListeResource finanzierungsVorschlaege(List<FinanzierungsVorschlag> finanzierungsVorschlaege) {
    this.finanzierungsVorschlaege = finanzierungsVorschlaege;
    return this;
  }

  public ErgebnisListeResource addFinanzierungsVorschlaegeItem(FinanzierungsVorschlag finanzierungsVorschlaegeItem) {
    if (this.finanzierungsVorschlaege == null) {
      this.finanzierungsVorschlaege = new ArrayList<FinanzierungsVorschlag>();
    }
    this.finanzierungsVorschlaege.add(finanzierungsVorschlaegeItem);
    return this;
  }

   /**
   * Get finanzierungsVorschlaege
   * @return finanzierungsVorschlaege
  **/
  @ApiModelProperty(value = "")
  public List<FinanzierungsVorschlag> getFinanzierungsVorschlaege() {
    return finanzierungsVorschlaege;
  }

  public void setFinanzierungsVorschlaege(List<FinanzierungsVorschlag> finanzierungsVorschlaege) {
    this.finanzierungsVorschlaege = finanzierungsVorschlaege;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErgebnisListeResource ergebnisListeResource = (ErgebnisListeResource) o;
    return Objects.equals(this.finanzierungsVorschlaege, ergebnisListeResource.finanzierungsVorschlaege);
  }

  @Override
  public int hashCode() {
    return Objects.hash(finanzierungsVorschlaege);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErgebnisListeResource {\n");
    
    sb.append("    finanzierungsVorschlaege: ").append(toIndentedString(finanzierungsVorschlaege)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

