/**
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 0.1
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import de.europace.eli.model.FinanzierungsVorschlag;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * ErgebnisListeResource
 */

public class ErgebnisListeResource   {
  @JsonProperty("finanzierungsVorschlaege")
  private List<FinanzierungsVorschlag> finanzierungsVorschlaege = new ArrayList<FinanzierungsVorschlag>();

  public ErgebnisListeResource finanzierungsVorschlaege(List<FinanzierungsVorschlag> finanzierungsVorschlaege) {
    this.finanzierungsVorschlaege = finanzierungsVorschlaege;
    return this;
  }

  public ErgebnisListeResource addFinanzierungsVorschlaegeItem(FinanzierungsVorschlag finanzierungsVorschlaegeItem) {
    this.finanzierungsVorschlaege.add(finanzierungsVorschlaegeItem);
    return this;
  }

   /**
   * Get finanzierungsVorschlaege
   * @return finanzierungsVorschlaege
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<FinanzierungsVorschlag> getFinanzierungsVorschlaege() {
    return finanzierungsVorschlaege;
  }

  public void setFinanzierungsVorschlaege(List<FinanzierungsVorschlag> finanzierungsVorschlaege) {
    this.finanzierungsVorschlaege = finanzierungsVorschlaege;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErgebnisListeResource ergebnisListeResource = (ErgebnisListeResource) o;
    return Objects.equals(this.finanzierungsVorschlaege, ergebnisListeResource.finanzierungsVorschlaege);
  }

  @Override
  public int hashCode() {
    return Objects.hash(finanzierungsVorschlaege);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErgebnisListeResource {\n");
    
    sb.append("    finanzierungsVorschlaege: ").append(toIndentedString(finanzierungsVorschlaege)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

