/*
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 1.0
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import de.europace.eli.model.Autostellplatz;
import de.europace.eli.model.BestehendesDarlehenDesFinanzierungsObjekts;
import de.europace.eli.model.EffektivZinsErhoehendeKosten;
import de.europace.eli.model.Erbbaurecht;
import de.europace.eli.model.Gebaeude;
import de.europace.eli.model.GrundbuchAngabe;
import de.europace.eli.model.Grundstueck;
import de.europace.eli.model.Postadresse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * FinanzierungsObjekt
 */

public class FinanzierungsObjekt {
  @JsonProperty("adresse")
  private Postadresse adresse = null;

  @JsonProperty("autostellplaetze")
  private List<Autostellplatz> autostellplaetze = null;

  @JsonProperty("bestehendeDarlehen")
  private List<BestehendesDarlehenDesFinanzierungsObjekts> bestehendeDarlehen = null;

  @JsonProperty("bewirtschaftungsKostenJaehrlich")
  private BigDecimal bewirtschaftungsKostenJaehrlich = null;

  @JsonProperty("bodenRichtwert")
  private BigDecimal bodenRichtwert = null;

  @JsonProperty("effektivZinsErhoehendeKosten")
  private EffektivZinsErhoehendeKosten effektivZinsErhoehendeKosten = null;

  @JsonProperty("erbbaurecht")
  private Erbbaurecht erbbaurecht = null;

  @JsonProperty("gebaeude")
  private Gebaeude gebaeude = null;

  @JsonProperty("grundbuchAngabe")
  private GrundbuchAngabe grundbuchAngabe = null;

  @JsonProperty("grundstueck")
  private Grundstueck grundstueck = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("keinBaulandFlaecheInQm")
  private BigDecimal keinBaulandFlaecheInQm = null;

  @JsonProperty("marktueblicherKaufpreisProQm")
  private BigDecimal marktueblicherKaufpreisProQm = null;

  /**
   * Gets or Sets objektArt
   */
  public enum ObjektArtEnum {
    GRUNDSTUECK("GRUNDSTUECK"),
    
    EIGENTUMSWOHNUNG("EIGENTUMSWOHNUNG"),
    
    HAUS("HAUS");

    private String value;

    ObjektArtEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ObjektArtEnum fromValue(String text) {
      for (ObjektArtEnum b : ObjektArtEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("objektArt")
  private ObjektArtEnum objektArt = null;

  @JsonProperty("vergleichsmieteFuerGewerbeflaecheProQm")
  private BigDecimal vergleichsmieteFuerGewerbeflaecheProQm = null;

  @JsonProperty("vergleichsmieteFuerWohnflaecheProQm")
  private BigDecimal vergleichsmieteFuerWohnflaecheProQm = null;

  @JsonProperty("verkehrswert")
  private BigDecimal verkehrswert = null;

  /**
   * Gets or Sets wohnlage
   */
  public enum WohnlageEnum {
    GEHOBEN("GEHOBEN"),
    
    MITTEL("MITTEL"),
    
    EINFACH("EINFACH");

    private String value;

    WohnlageEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static WohnlageEnum fromValue(String text) {
      for (WohnlageEnum b : WohnlageEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("wohnlage")
  private WohnlageEnum wohnlage = null;

  public FinanzierungsObjekt adresse(Postadresse adresse) {
    this.adresse = adresse;
    return this;
  }

   /**
   * Get adresse
   * @return adresse
  **/
  @ApiModelProperty(value = "")
  public Postadresse getAdresse() {
    return adresse;
  }

  public void setAdresse(Postadresse adresse) {
    this.adresse = adresse;
  }

  public FinanzierungsObjekt autostellplaetze(List<Autostellplatz> autostellplaetze) {
    this.autostellplaetze = autostellplaetze;
    return this;
  }

  public FinanzierungsObjekt addAutostellplaetzeItem(Autostellplatz autostellplaetzeItem) {
    if (this.autostellplaetze == null) {
      this.autostellplaetze = new ArrayList<Autostellplatz>();
    }
    this.autostellplaetze.add(autostellplaetzeItem);
    return this;
  }

   /**
   * Get autostellplaetze
   * @return autostellplaetze
  **/
  @ApiModelProperty(value = "")
  public List<Autostellplatz> getAutostellplaetze() {
    return autostellplaetze;
  }

  public void setAutostellplaetze(List<Autostellplatz> autostellplaetze) {
    this.autostellplaetze = autostellplaetze;
  }

  public FinanzierungsObjekt bestehendeDarlehen(List<BestehendesDarlehenDesFinanzierungsObjekts> bestehendeDarlehen) {
    this.bestehendeDarlehen = bestehendeDarlehen;
    return this;
  }

  public FinanzierungsObjekt addBestehendeDarlehenItem(BestehendesDarlehenDesFinanzierungsObjekts bestehendeDarlehenItem) {
    if (this.bestehendeDarlehen == null) {
      this.bestehendeDarlehen = new ArrayList<BestehendesDarlehenDesFinanzierungsObjekts>();
    }
    this.bestehendeDarlehen.add(bestehendeDarlehenItem);
    return this;
  }

   /**
   * Get bestehendeDarlehen
   * @return bestehendeDarlehen
  **/
  @ApiModelProperty(value = "")
  public List<BestehendesDarlehenDesFinanzierungsObjekts> getBestehendeDarlehen() {
    return bestehendeDarlehen;
  }

  public void setBestehendeDarlehen(List<BestehendesDarlehenDesFinanzierungsObjekts> bestehendeDarlehen) {
    this.bestehendeDarlehen = bestehendeDarlehen;
  }

  public FinanzierungsObjekt bewirtschaftungsKostenJaehrlich(BigDecimal bewirtschaftungsKostenJaehrlich) {
    this.bewirtschaftungsKostenJaehrlich = bewirtschaftungsKostenJaehrlich;
    return this;
  }

   /**
   * Get bewirtschaftungsKostenJaehrlich
   * @return bewirtschaftungsKostenJaehrlich
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getBewirtschaftungsKostenJaehrlich() {
    return bewirtschaftungsKostenJaehrlich;
  }

  public void setBewirtschaftungsKostenJaehrlich(BigDecimal bewirtschaftungsKostenJaehrlich) {
    this.bewirtschaftungsKostenJaehrlich = bewirtschaftungsKostenJaehrlich;
  }

  public FinanzierungsObjekt bodenRichtwert(BigDecimal bodenRichtwert) {
    this.bodenRichtwert = bodenRichtwert;
    return this;
  }

   /**
   * Get bodenRichtwert
   * @return bodenRichtwert
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getBodenRichtwert() {
    return bodenRichtwert;
  }

  public void setBodenRichtwert(BigDecimal bodenRichtwert) {
    this.bodenRichtwert = bodenRichtwert;
  }

  public FinanzierungsObjekt effektivZinsErhoehendeKosten(EffektivZinsErhoehendeKosten effektivZinsErhoehendeKosten) {
    this.effektivZinsErhoehendeKosten = effektivZinsErhoehendeKosten;
    return this;
  }

   /**
   * Effektivzinsbeeinflussende Kosten - Anpassungen nach PAngV
   * @return effektivZinsErhoehendeKosten
  **/
  @ApiModelProperty(value = "Effektivzinsbeeinflussende Kosten - Anpassungen nach PAngV")
  public EffektivZinsErhoehendeKosten getEffektivZinsErhoehendeKosten() {
    return effektivZinsErhoehendeKosten;
  }

  public void setEffektivZinsErhoehendeKosten(EffektivZinsErhoehendeKosten effektivZinsErhoehendeKosten) {
    this.effektivZinsErhoehendeKosten = effektivZinsErhoehendeKosten;
  }

  public FinanzierungsObjekt erbbaurecht(Erbbaurecht erbbaurecht) {
    this.erbbaurecht = erbbaurecht;
    return this;
  }

   /**
   * Get erbbaurecht
   * @return erbbaurecht
  **/
  @ApiModelProperty(value = "")
  public Erbbaurecht getErbbaurecht() {
    return erbbaurecht;
  }

  public void setErbbaurecht(Erbbaurecht erbbaurecht) {
    this.erbbaurecht = erbbaurecht;
  }

  public FinanzierungsObjekt gebaeude(Gebaeude gebaeude) {
    this.gebaeude = gebaeude;
    return this;
  }

   /**
   * Get gebaeude
   * @return gebaeude
  **/
  @ApiModelProperty(value = "")
  public Gebaeude getGebaeude() {
    return gebaeude;
  }

  public void setGebaeude(Gebaeude gebaeude) {
    this.gebaeude = gebaeude;
  }

  public FinanzierungsObjekt grundbuchAngabe(GrundbuchAngabe grundbuchAngabe) {
    this.grundbuchAngabe = grundbuchAngabe;
    return this;
  }

   /**
   * Get grundbuchAngabe
   * @return grundbuchAngabe
  **/
  @ApiModelProperty(value = "")
  public GrundbuchAngabe getGrundbuchAngabe() {
    return grundbuchAngabe;
  }

  public void setGrundbuchAngabe(GrundbuchAngabe grundbuchAngabe) {
    this.grundbuchAngabe = grundbuchAngabe;
  }

  public FinanzierungsObjekt grundstueck(Grundstueck grundstueck) {
    this.grundstueck = grundstueck;
    return this;
  }

   /**
   * Get grundstueck
   * @return grundstueck
  **/
  @ApiModelProperty(value = "")
  public Grundstueck getGrundstueck() {
    return grundstueck;
  }

  public void setGrundstueck(Grundstueck grundstueck) {
    this.grundstueck = grundstueck;
  }

  public FinanzierungsObjekt id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public FinanzierungsObjekt keinBaulandFlaecheInQm(BigDecimal keinBaulandFlaecheInQm) {
    this.keinBaulandFlaecheInQm = keinBaulandFlaecheInQm;
    return this;
  }

   /**
   * Dieses Feld ist eine produktanbieterspezifische Zusatzangabe, sie wird nicht von allen Produktanbietern bei der Angebotsermittlung berücksichtigt.
   * @return keinBaulandFlaecheInQm
  **/
  @ApiModelProperty(value = "Dieses Feld ist eine produktanbieterspezifische Zusatzangabe, sie wird nicht von allen Produktanbietern bei der Angebotsermittlung berücksichtigt.")
  public BigDecimal getKeinBaulandFlaecheInQm() {
    return keinBaulandFlaecheInQm;
  }

  public void setKeinBaulandFlaecheInQm(BigDecimal keinBaulandFlaecheInQm) {
    this.keinBaulandFlaecheInQm = keinBaulandFlaecheInQm;
  }

  public FinanzierungsObjekt marktueblicherKaufpreisProQm(BigDecimal marktueblicherKaufpreisProQm) {
    this.marktueblicherKaufpreisProQm = marktueblicherKaufpreisProQm;
    return this;
  }

   /**
   * Get marktueblicherKaufpreisProQm
   * @return marktueblicherKaufpreisProQm
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getMarktueblicherKaufpreisProQm() {
    return marktueblicherKaufpreisProQm;
  }

  public void setMarktueblicherKaufpreisProQm(BigDecimal marktueblicherKaufpreisProQm) {
    this.marktueblicherKaufpreisProQm = marktueblicherKaufpreisProQm;
  }

  public FinanzierungsObjekt objektArt(ObjektArtEnum objektArt) {
    this.objektArt = objektArt;
    return this;
  }

   /**
   * Get objektArt
   * @return objektArt
  **/
  @ApiModelProperty(value = "")
  public ObjektArtEnum getObjektArt() {
    return objektArt;
  }

  public void setObjektArt(ObjektArtEnum objektArt) {
    this.objektArt = objektArt;
  }

  public FinanzierungsObjekt vergleichsmieteFuerGewerbeflaecheProQm(BigDecimal vergleichsmieteFuerGewerbeflaecheProQm) {
    this.vergleichsmieteFuerGewerbeflaecheProQm = vergleichsmieteFuerGewerbeflaecheProQm;
    return this;
  }

   /**
   * Get vergleichsmieteFuerGewerbeflaecheProQm
   * @return vergleichsmieteFuerGewerbeflaecheProQm
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getVergleichsmieteFuerGewerbeflaecheProQm() {
    return vergleichsmieteFuerGewerbeflaecheProQm;
  }

  public void setVergleichsmieteFuerGewerbeflaecheProQm(BigDecimal vergleichsmieteFuerGewerbeflaecheProQm) {
    this.vergleichsmieteFuerGewerbeflaecheProQm = vergleichsmieteFuerGewerbeflaecheProQm;
  }

  public FinanzierungsObjekt vergleichsmieteFuerWohnflaecheProQm(BigDecimal vergleichsmieteFuerWohnflaecheProQm) {
    this.vergleichsmieteFuerWohnflaecheProQm = vergleichsmieteFuerWohnflaecheProQm;
    return this;
  }

   /**
   * Get vergleichsmieteFuerWohnflaecheProQm
   * @return vergleichsmieteFuerWohnflaecheProQm
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getVergleichsmieteFuerWohnflaecheProQm() {
    return vergleichsmieteFuerWohnflaecheProQm;
  }

  public void setVergleichsmieteFuerWohnflaecheProQm(BigDecimal vergleichsmieteFuerWohnflaecheProQm) {
    this.vergleichsmieteFuerWohnflaecheProQm = vergleichsmieteFuerWohnflaecheProQm;
  }

  public FinanzierungsObjekt verkehrswert(BigDecimal verkehrswert) {
    this.verkehrswert = verkehrswert;
    return this;
  }

   /**
   * Verkehrswert, nur relevant bei Finanzbedarf AnschlussFinanzierung, Modernisierung und Kapitalbeschaffung
   * @return verkehrswert
  **/
  @ApiModelProperty(value = "Verkehrswert, nur relevant bei Finanzbedarf AnschlussFinanzierung, Modernisierung und Kapitalbeschaffung")
  public BigDecimal getVerkehrswert() {
    return verkehrswert;
  }

  public void setVerkehrswert(BigDecimal verkehrswert) {
    this.verkehrswert = verkehrswert;
  }

  public FinanzierungsObjekt wohnlage(WohnlageEnum wohnlage) {
    this.wohnlage = wohnlage;
    return this;
  }

   /**
   * Get wohnlage
   * @return wohnlage
  **/
  @ApiModelProperty(value = "")
  public WohnlageEnum getWohnlage() {
    return wohnlage;
  }

  public void setWohnlage(WohnlageEnum wohnlage) {
    this.wohnlage = wohnlage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FinanzierungsObjekt finanzierungsObjekt = (FinanzierungsObjekt) o;
    return Objects.equals(this.adresse, finanzierungsObjekt.adresse) &&
        Objects.equals(this.autostellplaetze, finanzierungsObjekt.autostellplaetze) &&
        Objects.equals(this.bestehendeDarlehen, finanzierungsObjekt.bestehendeDarlehen) &&
        Objects.equals(this.bewirtschaftungsKostenJaehrlich, finanzierungsObjekt.bewirtschaftungsKostenJaehrlich) &&
        Objects.equals(this.bodenRichtwert, finanzierungsObjekt.bodenRichtwert) &&
        Objects.equals(this.effektivZinsErhoehendeKosten, finanzierungsObjekt.effektivZinsErhoehendeKosten) &&
        Objects.equals(this.erbbaurecht, finanzierungsObjekt.erbbaurecht) &&
        Objects.equals(this.gebaeude, finanzierungsObjekt.gebaeude) &&
        Objects.equals(this.grundbuchAngabe, finanzierungsObjekt.grundbuchAngabe) &&
        Objects.equals(this.grundstueck, finanzierungsObjekt.grundstueck) &&
        Objects.equals(this.id, finanzierungsObjekt.id) &&
        Objects.equals(this.keinBaulandFlaecheInQm, finanzierungsObjekt.keinBaulandFlaecheInQm) &&
        Objects.equals(this.marktueblicherKaufpreisProQm, finanzierungsObjekt.marktueblicherKaufpreisProQm) &&
        Objects.equals(this.objektArt, finanzierungsObjekt.objektArt) &&
        Objects.equals(this.vergleichsmieteFuerGewerbeflaecheProQm, finanzierungsObjekt.vergleichsmieteFuerGewerbeflaecheProQm) &&
        Objects.equals(this.vergleichsmieteFuerWohnflaecheProQm, finanzierungsObjekt.vergleichsmieteFuerWohnflaecheProQm) &&
        Objects.equals(this.verkehrswert, finanzierungsObjekt.verkehrswert) &&
        Objects.equals(this.wohnlage, finanzierungsObjekt.wohnlage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adresse, autostellplaetze, bestehendeDarlehen, bewirtschaftungsKostenJaehrlich, bodenRichtwert, effektivZinsErhoehendeKosten, erbbaurecht, gebaeude, grundbuchAngabe, grundstueck, id, keinBaulandFlaecheInQm, marktueblicherKaufpreisProQm, objektArt, vergleichsmieteFuerGewerbeflaecheProQm, vergleichsmieteFuerWohnflaecheProQm, verkehrswert, wohnlage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FinanzierungsObjekt {\n");
    
    sb.append("    adresse: ").append(toIndentedString(adresse)).append("\n");
    sb.append("    autostellplaetze: ").append(toIndentedString(autostellplaetze)).append("\n");
    sb.append("    bestehendeDarlehen: ").append(toIndentedString(bestehendeDarlehen)).append("\n");
    sb.append("    bewirtschaftungsKostenJaehrlich: ").append(toIndentedString(bewirtschaftungsKostenJaehrlich)).append("\n");
    sb.append("    bodenRichtwert: ").append(toIndentedString(bodenRichtwert)).append("\n");
    sb.append("    effektivZinsErhoehendeKosten: ").append(toIndentedString(effektivZinsErhoehendeKosten)).append("\n");
    sb.append("    erbbaurecht: ").append(toIndentedString(erbbaurecht)).append("\n");
    sb.append("    gebaeude: ").append(toIndentedString(gebaeude)).append("\n");
    sb.append("    grundbuchAngabe: ").append(toIndentedString(grundbuchAngabe)).append("\n");
    sb.append("    grundstueck: ").append(toIndentedString(grundstueck)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    keinBaulandFlaecheInQm: ").append(toIndentedString(keinBaulandFlaecheInQm)).append("\n");
    sb.append("    marktueblicherKaufpreisProQm: ").append(toIndentedString(marktueblicherKaufpreisProQm)).append("\n");
    sb.append("    objektArt: ").append(toIndentedString(objektArt)).append("\n");
    sb.append("    vergleichsmieteFuerGewerbeflaecheProQm: ").append(toIndentedString(vergleichsmieteFuerGewerbeflaecheProQm)).append("\n");
    sb.append("    vergleichsmieteFuerWohnflaecheProQm: ").append(toIndentedString(vergleichsmieteFuerWohnflaecheProQm)).append("\n");
    sb.append("    verkehrswert: ").append(toIndentedString(verkehrswert)).append("\n");
    sb.append("    wohnlage: ").append(toIndentedString(wohnlage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

