/*
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 1.0
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import de.europace.eli.model.TilgungsWunsch;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * ForwardDarlehensWunsch
 */

public class ForwardDarlehensWunsch {
  @JsonProperty("auszahlungsDatum")
  private LocalDate auszahlungsDatum = null;

  @JsonProperty("bereitstellungsZinsFreieZeitInMonaten")
  private Integer bereitstellungsZinsFreieZeitInMonaten = null;

  @JsonProperty("darlehensBetrag")
  private BigDecimal darlehensBetrag = null;

  @JsonProperty("provision")
  private BigDecimal provision = null;

  @JsonProperty("sondertilgungOptionalJaehrlich")
  private BigDecimal sondertilgungOptionalJaehrlich = null;

  @JsonProperty("tilgungsWunsch")
  private TilgungsWunsch tilgungsWunsch = null;

  @JsonProperty("zinsBindungInJahren")
  private Integer zinsBindungInJahren = null;

  public ForwardDarlehensWunsch auszahlungsDatum(LocalDate auszahlungsDatum) {
    this.auszahlungsDatum = auszahlungsDatum;
    return this;
  }

   /**
   * Get auszahlungsDatum
   * @return auszahlungsDatum
  **/
  @ApiModelProperty(value = "")
  public LocalDate getAuszahlungsDatum() {
    return auszahlungsDatum;
  }

  public void setAuszahlungsDatum(LocalDate auszahlungsDatum) {
    this.auszahlungsDatum = auszahlungsDatum;
  }

  public ForwardDarlehensWunsch bereitstellungsZinsFreieZeitInMonaten(Integer bereitstellungsZinsFreieZeitInMonaten) {
    this.bereitstellungsZinsFreieZeitInMonaten = bereitstellungsZinsFreieZeitInMonaten;
    return this;
  }

   /**
   * Get bereitstellungsZinsFreieZeitInMonaten
   * @return bereitstellungsZinsFreieZeitInMonaten
  **/
  @ApiModelProperty(value = "")
  public Integer getBereitstellungsZinsFreieZeitInMonaten() {
    return bereitstellungsZinsFreieZeitInMonaten;
  }

  public void setBereitstellungsZinsFreieZeitInMonaten(Integer bereitstellungsZinsFreieZeitInMonaten) {
    this.bereitstellungsZinsFreieZeitInMonaten = bereitstellungsZinsFreieZeitInMonaten;
  }

  public ForwardDarlehensWunsch darlehensBetrag(BigDecimal darlehensBetrag) {
    this.darlehensBetrag = darlehensBetrag;
    return this;
  }

   /**
   * Get darlehensBetrag
   * @return darlehensBetrag
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getDarlehensBetrag() {
    return darlehensBetrag;
  }

  public void setDarlehensBetrag(BigDecimal darlehensBetrag) {
    this.darlehensBetrag = darlehensBetrag;
  }

  public ForwardDarlehensWunsch provision(BigDecimal provision) {
    this.provision = provision;
    return this;
  }

   /**
   * Get provision
   * @return provision
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getProvision() {
    return provision;
  }

  public void setProvision(BigDecimal provision) {
    this.provision = provision;
  }

  public ForwardDarlehensWunsch sondertilgungOptionalJaehrlich(BigDecimal sondertilgungOptionalJaehrlich) {
    this.sondertilgungOptionalJaehrlich = sondertilgungOptionalJaehrlich;
    return this;
  }

   /**
   * Get sondertilgungOptionalJaehrlich
   * @return sondertilgungOptionalJaehrlich
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getSondertilgungOptionalJaehrlich() {
    return sondertilgungOptionalJaehrlich;
  }

  public void setSondertilgungOptionalJaehrlich(BigDecimal sondertilgungOptionalJaehrlich) {
    this.sondertilgungOptionalJaehrlich = sondertilgungOptionalJaehrlich;
  }

  public ForwardDarlehensWunsch tilgungsWunsch(TilgungsWunsch tilgungsWunsch) {
    this.tilgungsWunsch = tilgungsWunsch;
    return this;
  }

   /**
   * Get tilgungsWunsch
   * @return tilgungsWunsch
  **/
  @ApiModelProperty(required = true, value = "")
  public TilgungsWunsch getTilgungsWunsch() {
    return tilgungsWunsch;
  }

  public void setTilgungsWunsch(TilgungsWunsch tilgungsWunsch) {
    this.tilgungsWunsch = tilgungsWunsch;
  }

  public ForwardDarlehensWunsch zinsBindungInJahren(Integer zinsBindungInJahren) {
    this.zinsBindungInJahren = zinsBindungInJahren;
    return this;
  }

   /**
   * Get zinsBindungInJahren
   * @return zinsBindungInJahren
  **/
  @ApiModelProperty(value = "")
  public Integer getZinsBindungInJahren() {
    return zinsBindungInJahren;
  }

  public void setZinsBindungInJahren(Integer zinsBindungInJahren) {
    this.zinsBindungInJahren = zinsBindungInJahren;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForwardDarlehensWunsch forwardDarlehensWunsch = (ForwardDarlehensWunsch) o;
    return Objects.equals(this.auszahlungsDatum, forwardDarlehensWunsch.auszahlungsDatum) &&
        Objects.equals(this.bereitstellungsZinsFreieZeitInMonaten, forwardDarlehensWunsch.bereitstellungsZinsFreieZeitInMonaten) &&
        Objects.equals(this.darlehensBetrag, forwardDarlehensWunsch.darlehensBetrag) &&
        Objects.equals(this.provision, forwardDarlehensWunsch.provision) &&
        Objects.equals(this.sondertilgungOptionalJaehrlich, forwardDarlehensWunsch.sondertilgungOptionalJaehrlich) &&
        Objects.equals(this.tilgungsWunsch, forwardDarlehensWunsch.tilgungsWunsch) &&
        Objects.equals(this.zinsBindungInJahren, forwardDarlehensWunsch.zinsBindungInJahren);
  }

  @Override
  public int hashCode() {
    return Objects.hash(auszahlungsDatum, bereitstellungsZinsFreieZeitInMonaten, darlehensBetrag, provision, sondertilgungOptionalJaehrlich, tilgungsWunsch, zinsBindungInJahren);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForwardDarlehensWunsch {\n");
    
    sb.append("    auszahlungsDatum: ").append(toIndentedString(auszahlungsDatum)).append("\n");
    sb.append("    bereitstellungsZinsFreieZeitInMonaten: ").append(toIndentedString(bereitstellungsZinsFreieZeitInMonaten)).append("\n");
    sb.append("    darlehensBetrag: ").append(toIndentedString(darlehensBetrag)).append("\n");
    sb.append("    provision: ").append(toIndentedString(provision)).append("\n");
    sb.append("    sondertilgungOptionalJaehrlich: ").append(toIndentedString(sondertilgungOptionalJaehrlich)).append("\n");
    sb.append("    tilgungsWunsch: ").append(toIndentedString(tilgungsWunsch)).append("\n");
    sb.append("    zinsBindungInJahren: ").append(toIndentedString(zinsBindungInJahren)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

