/*
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 1.0
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * KfwDarlehensWunsch
 */

public class KfwDarlehensWunsch {
  @JsonProperty("darlehensBetrag")
  private BigDecimal darlehensBetrag = null;

  /**
   * Gets or Sets kfwEnergieEffizienzStandard
   */
  public enum KfwEnergieEffizienzStandardEnum {
    _40_PLUS("STANDARD_40_PLUS"),
    
    _40("STANDARD_40"),
    
    _55("STANDARD_55"),
    
    _70("STANDARD_70");

    private String value;

    KfwEnergieEffizienzStandardEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static KfwEnergieEffizienzStandardEnum fromValue(String text) {
      for (KfwEnergieEffizienzStandardEnum b : KfwEnergieEffizienzStandardEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("kfwEnergieEffizienzStandard")
  private KfwEnergieEffizienzStandardEnum kfwEnergieEffizienzStandard = null;

  /**
   * Gets or Sets kfwProgramm
   */
  public enum KfwProgrammEnum {
    _124("PROGRAMM_124"),
    
    _141("PROGRAMM_141"),
    
    _151("PROGRAMM_151"),
    
    _152("PROGRAMM_152"),
    
    _153("PROGRAMM_153"),
    
    _155("PROGRAMM_155"),
    
    _159("PROGRAMM_159"),
    
    _167("PROGRAMM_167");

    private String value;

    KfwProgrammEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static KfwProgrammEnum fromValue(String text) {
      for (KfwProgrammEnum b : KfwProgrammEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("kfwProgramm")
  private KfwProgrammEnum kfwProgramm = null;

  @JsonProperty("laufzeitInJahren")
  private Integer laufzeitInJahren = null;

  @JsonProperty("provision")
  private BigDecimal provision = null;

  @JsonProperty("tilgungsfreieAnlaufjahre")
  private Integer tilgungsfreieAnlaufjahre = null;

  @JsonProperty("zinsBindungInJahren")
  private Integer zinsBindungInJahren = null;

  public KfwDarlehensWunsch darlehensBetrag(BigDecimal darlehensBetrag) {
    this.darlehensBetrag = darlehensBetrag;
    return this;
  }

   /**
   * Get darlehensBetrag
   * @return darlehensBetrag
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getDarlehensBetrag() {
    return darlehensBetrag;
  }

  public void setDarlehensBetrag(BigDecimal darlehensBetrag) {
    this.darlehensBetrag = darlehensBetrag;
  }

  public KfwDarlehensWunsch kfwEnergieEffizienzStandard(KfwEnergieEffizienzStandardEnum kfwEnergieEffizienzStandard) {
    this.kfwEnergieEffizienzStandard = kfwEnergieEffizienzStandard;
    return this;
  }

   /**
   * Get kfwEnergieEffizienzStandard
   * @return kfwEnergieEffizienzStandard
  **/
  @ApiModelProperty(value = "")
  public KfwEnergieEffizienzStandardEnum getKfwEnergieEffizienzStandard() {
    return kfwEnergieEffizienzStandard;
  }

  public void setKfwEnergieEffizienzStandard(KfwEnergieEffizienzStandardEnum kfwEnergieEffizienzStandard) {
    this.kfwEnergieEffizienzStandard = kfwEnergieEffizienzStandard;
  }

  public KfwDarlehensWunsch kfwProgramm(KfwProgrammEnum kfwProgramm) {
    this.kfwProgramm = kfwProgramm;
    return this;
  }

   /**
   * Get kfwProgramm
   * @return kfwProgramm
  **/
  @ApiModelProperty(value = "")
  public KfwProgrammEnum getKfwProgramm() {
    return kfwProgramm;
  }

  public void setKfwProgramm(KfwProgrammEnum kfwProgramm) {
    this.kfwProgramm = kfwProgramm;
  }

  public KfwDarlehensWunsch laufzeitInJahren(Integer laufzeitInJahren) {
    this.laufzeitInJahren = laufzeitInJahren;
    return this;
  }

   /**
   * Get laufzeitInJahren
   * @return laufzeitInJahren
  **/
  @ApiModelProperty(value = "")
  public Integer getLaufzeitInJahren() {
    return laufzeitInJahren;
  }

  public void setLaufzeitInJahren(Integer laufzeitInJahren) {
    this.laufzeitInJahren = laufzeitInJahren;
  }

  public KfwDarlehensWunsch provision(BigDecimal provision) {
    this.provision = provision;
    return this;
  }

   /**
   * Get provision
   * @return provision
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getProvision() {
    return provision;
  }

  public void setProvision(BigDecimal provision) {
    this.provision = provision;
  }

  public KfwDarlehensWunsch tilgungsfreieAnlaufjahre(Integer tilgungsfreieAnlaufjahre) {
    this.tilgungsfreieAnlaufjahre = tilgungsfreieAnlaufjahre;
    return this;
  }

   /**
   * Erlaubt ist 1,2,3,4,5. Maximalwert abhängig von der Laufzeit
   * @return tilgungsfreieAnlaufjahre
  **/
  @ApiModelProperty(value = "Erlaubt ist 1,2,3,4,5. Maximalwert abhängig von der Laufzeit")
  public Integer getTilgungsfreieAnlaufjahre() {
    return tilgungsfreieAnlaufjahre;
  }

  public void setTilgungsfreieAnlaufjahre(Integer tilgungsfreieAnlaufjahre) {
    this.tilgungsfreieAnlaufjahre = tilgungsfreieAnlaufjahre;
  }

  public KfwDarlehensWunsch zinsBindungInJahren(Integer zinsBindungInJahren) {
    this.zinsBindungInJahren = zinsBindungInJahren;
    return this;
  }

   /**
   * Programm 124: 5 oder 10, sonst: 10 oder 20
   * @return zinsBindungInJahren
  **/
  @ApiModelProperty(value = "Programm 124: 5 oder 10, sonst: 10 oder 20")
  public Integer getZinsBindungInJahren() {
    return zinsBindungInJahren;
  }

  public void setZinsBindungInJahren(Integer zinsBindungInJahren) {
    this.zinsBindungInJahren = zinsBindungInJahren;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KfwDarlehensWunsch kfwDarlehensWunsch = (KfwDarlehensWunsch) o;
    return Objects.equals(this.darlehensBetrag, kfwDarlehensWunsch.darlehensBetrag) &&
        Objects.equals(this.kfwEnergieEffizienzStandard, kfwDarlehensWunsch.kfwEnergieEffizienzStandard) &&
        Objects.equals(this.kfwProgramm, kfwDarlehensWunsch.kfwProgramm) &&
        Objects.equals(this.laufzeitInJahren, kfwDarlehensWunsch.laufzeitInJahren) &&
        Objects.equals(this.provision, kfwDarlehensWunsch.provision) &&
        Objects.equals(this.tilgungsfreieAnlaufjahre, kfwDarlehensWunsch.tilgungsfreieAnlaufjahre) &&
        Objects.equals(this.zinsBindungInJahren, kfwDarlehensWunsch.zinsBindungInJahren);
  }

  @Override
  public int hashCode() {
    return Objects.hash(darlehensBetrag, kfwEnergieEffizienzStandard, kfwProgramm, laufzeitInJahren, provision, tilgungsfreieAnlaufjahre, zinsBindungInJahren);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KfwDarlehensWunsch {\n");
    
    sb.append("    darlehensBetrag: ").append(toIndentedString(darlehensBetrag)).append("\n");
    sb.append("    kfwEnergieEffizienzStandard: ").append(toIndentedString(kfwEnergieEffizienzStandard)).append("\n");
    sb.append("    kfwProgramm: ").append(toIndentedString(kfwProgramm)).append("\n");
    sb.append("    laufzeitInJahren: ").append(toIndentedString(laufzeitInJahren)).append("\n");
    sb.append("    provision: ").append(toIndentedString(provision)).append("\n");
    sb.append("    tilgungsfreieAnlaufjahre: ").append(toIndentedString(tilgungsfreieAnlaufjahre)).append("\n");
    sb.append("    zinsBindungInJahren: ").append(toIndentedString(zinsBindungInJahren)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

