/*
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 1.0
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Kind
 */

public class Kind {
  @JsonProperty("geburtsdatum")
  private LocalDate geburtsdatum = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("kindergeldWirdBezogen")
  private Boolean kindergeldWirdBezogen = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("unterhaltsEinnahmenBetragMonatlich")
  private BigDecimal unterhaltsEinnahmenBetragMonatlich = null;

  public Kind geburtsdatum(LocalDate geburtsdatum) {
    this.geburtsdatum = geburtsdatum;
    return this;
  }

   /**
   * Get geburtsdatum
   * @return geburtsdatum
  **/
  @ApiModelProperty(value = "")
  public LocalDate getGeburtsdatum() {
    return geburtsdatum;
  }

  public void setGeburtsdatum(LocalDate geburtsdatum) {
    this.geburtsdatum = geburtsdatum;
  }

  public Kind id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Kind kindergeldWirdBezogen(Boolean kindergeldWirdBezogen) {
    this.kindergeldWirdBezogen = kindergeldWirdBezogen;
    return this;
  }

   /**
   * Get kindergeldWirdBezogen
   * @return kindergeldWirdBezogen
  **/
  @ApiModelProperty(value = "")
  public Boolean getKindergeldWirdBezogen() {
    return kindergeldWirdBezogen;
  }

  public void setKindergeldWirdBezogen(Boolean kindergeldWirdBezogen) {
    this.kindergeldWirdBezogen = kindergeldWirdBezogen;
  }

  public Kind name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Kind unterhaltsEinnahmenBetragMonatlich(BigDecimal unterhaltsEinnahmenBetragMonatlich) {
    this.unterhaltsEinnahmenBetragMonatlich = unterhaltsEinnahmenBetragMonatlich;
    return this;
  }

   /**
   * Get unterhaltsEinnahmenBetragMonatlich
   * @return unterhaltsEinnahmenBetragMonatlich
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getUnterhaltsEinnahmenBetragMonatlich() {
    return unterhaltsEinnahmenBetragMonatlich;
  }

  public void setUnterhaltsEinnahmenBetragMonatlich(BigDecimal unterhaltsEinnahmenBetragMonatlich) {
    this.unterhaltsEinnahmenBetragMonatlich = unterhaltsEinnahmenBetragMonatlich;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Kind kind = (Kind) o;
    return Objects.equals(this.geburtsdatum, kind.geburtsdatum) &&
        Objects.equals(this.id, kind.id) &&
        Objects.equals(this.kindergeldWirdBezogen, kind.kindergeldWirdBezogen) &&
        Objects.equals(this.name, kind.name) &&
        Objects.equals(this.unterhaltsEinnahmenBetragMonatlich, kind.unterhaltsEinnahmenBetragMonatlich);
  }

  @Override
  public int hashCode() {
    return Objects.hash(geburtsdatum, id, kindergeldWirdBezogen, name, unterhaltsEinnahmenBetragMonatlich);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Kind {\n");
    
    sb.append("    geburtsdatum: ").append(toIndentedString(geburtsdatum)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    kindergeldWirdBezogen: ").append(toIndentedString(kindergeldWirdBezogen)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    unterhaltsEinnahmenBetragMonatlich: ").append(toIndentedString(unterhaltsEinnahmenBetragMonatlich)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

