/**
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 0.1
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import de.europace.eli.model.Jahreszahl;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * LaufzeitPraeferenz
 */

public class LaufzeitPraeferenz   {
  @JsonProperty("bisZumJahr")
  private Jahreszahl bisZumJahr = null;

  @JsonProperty("bisZurRenteImJahr")
  private Jahreszahl bisZurRenteImJahr = null;

  @JsonProperty("inJahren")
  private Integer inJahren = null;

  @JsonProperty("praeferenzAuswahl")
  private String praeferenzAuswahl = null;

  @JsonProperty("zusatzlicheKommentare")
  private String zusatzlicheKommentare = null;

  public LaufzeitPraeferenz bisZumJahr(Jahreszahl bisZumJahr) {
    this.bisZumJahr = bisZumJahr;
    return this;
  }

   /**
   * Nur relevant, wenn praeferenzAuswahl==BIS_ZUM_JAHR. Vierstellige Jahresangabe
   * @return bisZumJahr
  **/
  @ApiModelProperty(example = "null", value = "Nur relevant, wenn praeferenzAuswahl==BIS_ZUM_JAHR. Vierstellige Jahresangabe")
  public Jahreszahl getBisZumJahr() {
    return bisZumJahr;
  }

  public void setBisZumJahr(Jahreszahl bisZumJahr) {
    this.bisZumJahr = bisZumJahr;
  }

  public LaufzeitPraeferenz bisZurRenteImJahr(Jahreszahl bisZurRenteImJahr) {
    this.bisZurRenteImJahr = bisZurRenteImJahr;
    return this;
  }

   /**
   * Nur relevant, wenn praeferenzAuswahl==BIS_ZUR_RENTE_IM_JAHR. Vierstellige Jahresangabe
   * @return bisZurRenteImJahr
  **/
  @ApiModelProperty(example = "null", value = "Nur relevant, wenn praeferenzAuswahl==BIS_ZUR_RENTE_IM_JAHR. Vierstellige Jahresangabe")
  public Jahreszahl getBisZurRenteImJahr() {
    return bisZurRenteImJahr;
  }

  public void setBisZurRenteImJahr(Jahreszahl bisZurRenteImJahr) {
    this.bisZurRenteImJahr = bisZurRenteImJahr;
  }

  public LaufzeitPraeferenz inJahren(Integer inJahren) {
    this.inJahren = inJahren;
    return this;
  }

   /**
   * Nur relevant, wenn praeferenzAuswahl==IN_JAHREN.
   * @return inJahren
  **/
  @ApiModelProperty(example = "null", value = "Nur relevant, wenn praeferenzAuswahl==IN_JAHREN.")
  public Integer getInJahren() {
    return inJahren;
  }

  public void setInJahren(Integer inJahren) {
    this.inJahren = inJahren;
  }

  public LaufzeitPraeferenz praeferenzAuswahl(String praeferenzAuswahl) {
    this.praeferenzAuswahl = praeferenzAuswahl;
    return this;
  }

   /**
   * MOEGLICHST_SCHNELL,IN_JAHREN,BIS_ZUM_JAHR,BIS_ZUR_RENTE_IM_JAHR,EGAL
   * @return praeferenzAuswahl
  **/
  @ApiModelProperty(example = "null", value = "MOEGLICHST_SCHNELL,IN_JAHREN,BIS_ZUM_JAHR,BIS_ZUR_RENTE_IM_JAHR,EGAL")
  public String getPraeferenzAuswahl() {
    return praeferenzAuswahl;
  }

  public void setPraeferenzAuswahl(String praeferenzAuswahl) {
    this.praeferenzAuswahl = praeferenzAuswahl;
  }

  public LaufzeitPraeferenz zusatzlicheKommentare(String zusatzlicheKommentare) {
    this.zusatzlicheKommentare = zusatzlicheKommentare;
    return this;
  }

   /**
   * Get zusatzlicheKommentare
   * @return zusatzlicheKommentare
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getZusatzlicheKommentare() {
    return zusatzlicheKommentare;
  }

  public void setZusatzlicheKommentare(String zusatzlicheKommentare) {
    this.zusatzlicheKommentare = zusatzlicheKommentare;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LaufzeitPraeferenz laufzeitPraeferenz = (LaufzeitPraeferenz) o;
    return Objects.equals(this.bisZumJahr, laufzeitPraeferenz.bisZumJahr) &&
        Objects.equals(this.bisZurRenteImJahr, laufzeitPraeferenz.bisZurRenteImJahr) &&
        Objects.equals(this.inJahren, laufzeitPraeferenz.inJahren) &&
        Objects.equals(this.praeferenzAuswahl, laufzeitPraeferenz.praeferenzAuswahl) &&
        Objects.equals(this.zusatzlicheKommentare, laufzeitPraeferenz.zusatzlicheKommentare);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bisZumJahr, bisZurRenteImJahr, inJahren, praeferenzAuswahl, zusatzlicheKommentare);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LaufzeitPraeferenz {\n");
    
    sb.append("    bisZumJahr: ").append(toIndentedString(bisZumJahr)).append("\n");
    sb.append("    bisZurRenteImJahr: ").append(toIndentedString(bisZurRenteImJahr)).append("\n");
    sb.append("    inJahren: ").append(toIndentedString(inJahren)).append("\n");
    sb.append("    praeferenzAuswahl: ").append(toIndentedString(praeferenzAuswahl)).append("\n");
    sb.append("    zusatzlicheKommentare: ").append(toIndentedString(zusatzlicheKommentare)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

