/*
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 0.1
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import de.europace.eli.model.Jahreszahl;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ModernisierungsAngaben
 */

public class ModernisierungsAngaben {
  @JsonProperty("modernisierungsGrad")
  private String modernisierungsGrad = null;

  @JsonProperty("modernisierungsJahr")
  private Jahreszahl modernisierungsJahr = null;

  public ModernisierungsAngaben modernisierungsGrad(String modernisierungsGrad) {
    this.modernisierungsGrad = modernisierungsGrad;
    return this;
  }

   /**
   * erlaubt sind GERING,MITTEL,HOCH. Neue Ausprägungen können kurzfristig hinzukommen. Der Client muss daher mit unbekannten Werten umgehen können.
   * @return modernisierungsGrad
  **/
  @ApiModelProperty(example = "null", value = "erlaubt sind GERING,MITTEL,HOCH. Neue Ausprägungen können kurzfristig hinzukommen. Der Client muss daher mit unbekannten Werten umgehen können.")
  public String getModernisierungsGrad() {
    return modernisierungsGrad;
  }

  public void setModernisierungsGrad(String modernisierungsGrad) {
    this.modernisierungsGrad = modernisierungsGrad;
  }

  public ModernisierungsAngaben modernisierungsJahr(Jahreszahl modernisierungsJahr) {
    this.modernisierungsJahr = modernisierungsJahr;
    return this;
  }

   /**
   * Jahr der Modernisierung der Immobilie. Vierstellige Jahresangabe
   * @return modernisierungsJahr
  **/
  @ApiModelProperty(example = "null", value = "Jahr der Modernisierung der Immobilie. Vierstellige Jahresangabe")
  public Jahreszahl getModernisierungsJahr() {
    return modernisierungsJahr;
  }

  public void setModernisierungsJahr(Jahreszahl modernisierungsJahr) {
    this.modernisierungsJahr = modernisierungsJahr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModernisierungsAngaben modernisierungsAngaben = (ModernisierungsAngaben) o;
    return Objects.equals(this.modernisierungsGrad, modernisierungsAngaben.modernisierungsGrad) &&
        Objects.equals(this.modernisierungsJahr, modernisierungsAngaben.modernisierungsJahr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(modernisierungsGrad, modernisierungsJahr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModernisierungsAngaben {\n");
    
    sb.append("    modernisierungsGrad: ").append(toIndentedString(modernisierungsGrad)).append("\n");
    sb.append("    modernisierungsJahr: ").append(toIndentedString(modernisierungsJahr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

