/**
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 0.1
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import de.europace.eli.model.ZinsBindung;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;


/**
 * NachrangigesExternesDarlehen
 */

public class NachrangigesExternesDarlehen   {
  @JsonProperty("darlehensBetrag")
  private BigDecimal darlehensBetrag = null;

  @JsonProperty("darlehensGeber")
  private String darlehensGeber = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("rateMonatlich")
  private BigDecimal rateMonatlich = null;

  @JsonProperty("typ")
  private String typ = null;

  @JsonProperty("zinsBindung")
  private ZinsBindung zinsBindung = null;

  public NachrangigesExternesDarlehen darlehensBetrag(BigDecimal darlehensBetrag) {
    this.darlehensBetrag = darlehensBetrag;
    return this;
  }

   /**
   * Get darlehensBetrag
   * @return darlehensBetrag
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getDarlehensBetrag() {
    return darlehensBetrag;
  }

  public void setDarlehensBetrag(BigDecimal darlehensBetrag) {
    this.darlehensBetrag = darlehensBetrag;
  }

  public NachrangigesExternesDarlehen darlehensGeber(String darlehensGeber) {
    this.darlehensGeber = darlehensGeber;
    return this;
  }

   /**
   * Der Name des externen Darlehensgebers (Firmierung). Es gibt keine entsprechende Beziehung zu einem Partner auf der Europace-Plattform.
   * @return darlehensGeber
  **/
  @ApiModelProperty(example = "null", value = "Der Name des externen Darlehensgebers (Firmierung). Es gibt keine entsprechende Beziehung zu einem Partner auf der Europace-Plattform.")
  public String getDarlehensGeber() {
    return darlehensGeber;
  }

  public void setDarlehensGeber(String darlehensGeber) {
    this.darlehensGeber = darlehensGeber;
  }

  public NachrangigesExternesDarlehen id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public NachrangigesExternesDarlehen rateMonatlich(BigDecimal rateMonatlich) {
    this.rateMonatlich = rateMonatlich;
    return this;
  }

   /**
   * Get rateMonatlich
   * @return rateMonatlich
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getRateMonatlich() {
    return rateMonatlich;
  }

  public void setRateMonatlich(BigDecimal rateMonatlich) {
    this.rateMonatlich = rateMonatlich;
  }

  public NachrangigesExternesDarlehen typ(String typ) {
    this.typ = typ;
    return this;
  }

   /**
   * Erlaubte Werte sind: ARBEITGEBERDARLEHEN,BAUSPARDARLEHEN,OEFFENTLICHES_DARLEHEN,RATENKREDIT. Neue Ausprägungen können kurzfristig hinzukommen. Der Client muss daher mit unbekannten Werten umgehen können.
   * @return typ
  **/
  @ApiModelProperty(example = "null", value = "Erlaubte Werte sind: ARBEITGEBERDARLEHEN,BAUSPARDARLEHEN,OEFFENTLICHES_DARLEHEN,RATENKREDIT. Neue Ausprägungen können kurzfristig hinzukommen. Der Client muss daher mit unbekannten Werten umgehen können.")
  public String getTyp() {
    return typ;
  }

  public void setTyp(String typ) {
    this.typ = typ;
  }

  public NachrangigesExternesDarlehen zinsBindung(ZinsBindung zinsBindung) {
    this.zinsBindung = zinsBindung;
    return this;
  }

   /**
   * Get zinsBindung
   * @return zinsBindung
  **/
  @ApiModelProperty(example = "null", value = "")
  public ZinsBindung getZinsBindung() {
    return zinsBindung;
  }

  public void setZinsBindung(ZinsBindung zinsBindung) {
    this.zinsBindung = zinsBindung;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NachrangigesExternesDarlehen nachrangigesExternesDarlehen = (NachrangigesExternesDarlehen) o;
    return Objects.equals(this.darlehensBetrag, nachrangigesExternesDarlehen.darlehensBetrag) &&
        Objects.equals(this.darlehensGeber, nachrangigesExternesDarlehen.darlehensGeber) &&
        Objects.equals(this.id, nachrangigesExternesDarlehen.id) &&
        Objects.equals(this.rateMonatlich, nachrangigesExternesDarlehen.rateMonatlich) &&
        Objects.equals(this.typ, nachrangigesExternesDarlehen.typ) &&
        Objects.equals(this.zinsBindung, nachrangigesExternesDarlehen.zinsBindung);
  }

  @Override
  public int hashCode() {
    return Objects.hash(darlehensBetrag, darlehensGeber, id, rateMonatlich, typ, zinsBindung);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NachrangigesExternesDarlehen {\n");
    
    sb.append("    darlehensBetrag: ").append(toIndentedString(darlehensBetrag)).append("\n");
    sb.append("    darlehensGeber: ").append(toIndentedString(darlehensGeber)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rateMonatlich: ").append(toIndentedString(rateMonatlich)).append("\n");
    sb.append("    typ: ").append(toIndentedString(typ)).append("\n");
    sb.append("    zinsBindung: ").append(toIndentedString(zinsBindung)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

