/*
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 1.0
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * PrivatDarlehensWunsch
 */

public class PrivatDarlehensWunsch {
  @JsonProperty("darlehensBetrag")
  private BigDecimal darlehensBetrag = null;

  @JsonProperty("laufzeitInMonaten")
  private Integer laufzeitInMonaten = null;

  @JsonProperty("provision")
  private BigDecimal provision = null;

  public PrivatDarlehensWunsch darlehensBetrag(BigDecimal darlehensBetrag) {
    this.darlehensBetrag = darlehensBetrag;
    return this;
  }

   /**
   * Get darlehensBetrag
   * @return darlehensBetrag
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getDarlehensBetrag() {
    return darlehensBetrag;
  }

  public void setDarlehensBetrag(BigDecimal darlehensBetrag) {
    this.darlehensBetrag = darlehensBetrag;
  }

  public PrivatDarlehensWunsch laufzeitInMonaten(Integer laufzeitInMonaten) {
    this.laufzeitInMonaten = laufzeitInMonaten;
    return this;
  }

   /**
   * Get laufzeitInMonaten
   * @return laufzeitInMonaten
  **/
  @ApiModelProperty(value = "")
  public Integer getLaufzeitInMonaten() {
    return laufzeitInMonaten;
  }

  public void setLaufzeitInMonaten(Integer laufzeitInMonaten) {
    this.laufzeitInMonaten = laufzeitInMonaten;
  }

  public PrivatDarlehensWunsch provision(BigDecimal provision) {
    this.provision = provision;
    return this;
  }

   /**
   * Get provision
   * @return provision
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getProvision() {
    return provision;
  }

  public void setProvision(BigDecimal provision) {
    this.provision = provision;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrivatDarlehensWunsch privatDarlehensWunsch = (PrivatDarlehensWunsch) o;
    return Objects.equals(this.darlehensBetrag, privatDarlehensWunsch.darlehensBetrag) &&
        Objects.equals(this.laufzeitInMonaten, privatDarlehensWunsch.laufzeitInMonaten) &&
        Objects.equals(this.provision, privatDarlehensWunsch.provision);
  }

  @Override
  public int hashCode() {
    return Objects.hash(darlehensBetrag, laufzeitInMonaten, provision);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrivatDarlehensWunsch {\n");
    
    sb.append("    darlehensBetrag: ").append(toIndentedString(darlehensBetrag)).append("\n");
    sb.append("    laufzeitInMonaten: ").append(toIndentedString(laufzeitInMonaten)).append("\n");
    sb.append("    provision: ").append(toIndentedString(provision)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

