/*
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 0.1
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ProduktAnbieter
 */

public class ProduktAnbieter {
  @JsonProperty("email")
  private String email = null;

  @JsonProperty("firmierung")
  private String firmierung = null;

  @JsonProperty("nachname")
  private String nachname = null;

  @JsonProperty("partnerId")
  private String partnerId = null;

  @JsonProperty("produktAnbieterId")
  private String produktAnbieterId = null;

  @JsonProperty("telefonnummer")
  private String telefonnummer = null;

  @JsonProperty("vorname")
  private String vorname = null;

  public ProduktAnbieter email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public ProduktAnbieter firmierung(String firmierung) {
    this.firmierung = firmierung;
    return this;
  }

   /**
   * Get firmierung
   * @return firmierung
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFirmierung() {
    return firmierung;
  }

  public void setFirmierung(String firmierung) {
    this.firmierung = firmierung;
  }

  public ProduktAnbieter nachname(String nachname) {
    this.nachname = nachname;
    return this;
  }

   /**
   * Get nachname
   * @return nachname
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getNachname() {
    return nachname;
  }

  public void setNachname(String nachname) {
    this.nachname = nachname;
  }

  public ProduktAnbieter partnerId(String partnerId) {
    this.partnerId = partnerId;
    return this;
  }

   /**
   * Get partnerId
   * @return partnerId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPartnerId() {
    return partnerId;
  }

  public void setPartnerId(String partnerId) {
    this.partnerId = partnerId;
  }

  public ProduktAnbieter produktAnbieterId(String produktAnbieterId) {
    this.produktAnbieterId = produktAnbieterId;
    return this;
  }

   /**
   * Get produktAnbieterId
   * @return produktAnbieterId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getProduktAnbieterId() {
    return produktAnbieterId;
  }

  public void setProduktAnbieterId(String produktAnbieterId) {
    this.produktAnbieterId = produktAnbieterId;
  }

  public ProduktAnbieter telefonnummer(String telefonnummer) {
    this.telefonnummer = telefonnummer;
    return this;
  }

   /**
   * Get telefonnummer
   * @return telefonnummer
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTelefonnummer() {
    return telefonnummer;
  }

  public void setTelefonnummer(String telefonnummer) {
    this.telefonnummer = telefonnummer;
  }

  public ProduktAnbieter vorname(String vorname) {
    this.vorname = vorname;
    return this;
  }

   /**
   * Get vorname
   * @return vorname
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVorname() {
    return vorname;
  }

  public void setVorname(String vorname) {
    this.vorname = vorname;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProduktAnbieter produktAnbieter = (ProduktAnbieter) o;
    return Objects.equals(this.email, produktAnbieter.email) &&
        Objects.equals(this.firmierung, produktAnbieter.firmierung) &&
        Objects.equals(this.nachname, produktAnbieter.nachname) &&
        Objects.equals(this.partnerId, produktAnbieter.partnerId) &&
        Objects.equals(this.produktAnbieterId, produktAnbieter.produktAnbieterId) &&
        Objects.equals(this.telefonnummer, produktAnbieter.telefonnummer) &&
        Objects.equals(this.vorname, produktAnbieter.vorname);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, firmierung, nachname, partnerId, produktAnbieterId, telefonnummer, vorname);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProduktAnbieter {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    firmierung: ").append(toIndentedString(firmierung)).append("\n");
    sb.append("    nachname: ").append(toIndentedString(nachname)).append("\n");
    sb.append("    partnerId: ").append(toIndentedString(partnerId)).append("\n");
    sb.append("    produktAnbieterId: ").append(toIndentedString(produktAnbieterId)).append("\n");
    sb.append("    telefonnummer: ").append(toIndentedString(telefonnummer)).append("\n");
    sb.append("    vorname: ").append(toIndentedString(vorname)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

