/*
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 0.1
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * Provision
 */

public class Provision {
  @JsonProperty("provisionAbsolut")
  private BigDecimal provisionAbsolut = null;

  @JsonProperty("provisionRelativ")
  private BigDecimal provisionRelativ = null;

  public Provision provisionAbsolut(BigDecimal provisionAbsolut) {
    this.provisionAbsolut = provisionAbsolut;
    return this;
  }

   /**
   * Get provisionAbsolut
   * @return provisionAbsolut
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getProvisionAbsolut() {
    return provisionAbsolut;
  }

  public void setProvisionAbsolut(BigDecimal provisionAbsolut) {
    this.provisionAbsolut = provisionAbsolut;
  }

  public Provision provisionRelativ(BigDecimal provisionRelativ) {
    this.provisionRelativ = provisionRelativ;
    return this;
  }

   /**
   * Get provisionRelativ
   * @return provisionRelativ
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getProvisionRelativ() {
    return provisionRelativ;
  }

  public void setProvisionRelativ(BigDecimal provisionRelativ) {
    this.provisionRelativ = provisionRelativ;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Provision provision = (Provision) o;
    return Objects.equals(this.provisionAbsolut, provision.provisionAbsolut) &&
        Objects.equals(this.provisionRelativ, provision.provisionRelativ);
  }

  @Override
  public int hashCode() {
    return Objects.hash(provisionAbsolut, provisionRelativ);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Provision {\n");
    
    sb.append("    provisionAbsolut: ").append(toIndentedString(provisionAbsolut)).append("\n");
    sb.append("    provisionRelativ: ").append(toIndentedString(provisionRelativ)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

