/**
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 0.1
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import de.europace.eli.model.BausparWunsch;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.joda.time.LocalDate;


/**
 * TilgungsWunsch
 */

public class TilgungsWunsch   {
  @JsonProperty("anfaenglicheTilgung")
  private BigDecimal anfaenglicheTilgung = null;

  @JsonProperty("ausgesetztBerechnet")
  private Boolean ausgesetztBerechnet = null;

  @JsonProperty("ausgesetztEigenesAngebot")
  private Boolean ausgesetztEigenesAngebot = null;

  @JsonProperty("bausparWunsch")
  private BausparWunsch bausparWunsch = null;

  @JsonProperty("rate")
  private BigDecimal rate = null;

  @JsonProperty("tilgungsBeginn")
  private LocalDate tilgungsBeginn = null;

  @JsonProperty("tilgungsErsatzProduktId")
  private String tilgungsErsatzProduktId = null;

  @JsonProperty("volltilgerWennAnnuitaetenOderForward")
  private Boolean volltilgerWennAnnuitaetenOderForward = null;

  public TilgungsWunsch anfaenglicheTilgung(BigDecimal anfaenglicheTilgung) {
    this.anfaenglicheTilgung = anfaenglicheTilgung;
    return this;
  }

   /**
   * muss leer sein, wenn eines der anderen Attribute gefüllt ist
   * @return anfaenglicheTilgung
  **/
  @ApiModelProperty(example = "null", value = "muss leer sein, wenn eines der anderen Attribute gefüllt ist")
  public BigDecimal getAnfaenglicheTilgung() {
    return anfaenglicheTilgung;
  }

  public void setAnfaenglicheTilgung(BigDecimal anfaenglicheTilgung) {
    this.anfaenglicheTilgung = anfaenglicheTilgung;
  }

  public TilgungsWunsch ausgesetztBerechnet(Boolean ausgesetztBerechnet) {
    this.ausgesetztBerechnet = ausgesetztBerechnet;
    return this;
  }

   /**
   * muss leer sein, wenn eines der anderen Attribute gefüllt ist
   * @return ausgesetztBerechnet
  **/
  @ApiModelProperty(example = "false", value = "muss leer sein, wenn eines der anderen Attribute gefüllt ist")
  public Boolean getAusgesetztBerechnet() {
    return ausgesetztBerechnet;
  }

  public void setAusgesetztBerechnet(Boolean ausgesetztBerechnet) {
    this.ausgesetztBerechnet = ausgesetztBerechnet;
  }

  public TilgungsWunsch ausgesetztEigenesAngebot(Boolean ausgesetztEigenesAngebot) {
    this.ausgesetztEigenesAngebot = ausgesetztEigenesAngebot;
    return this;
  }

   /**
   * muss leer sein, wenn eines der anderen Attribute gefüllt ist
   * @return ausgesetztEigenesAngebot
  **/
  @ApiModelProperty(example = "false", value = "muss leer sein, wenn eines der anderen Attribute gefüllt ist")
  public Boolean getAusgesetztEigenesAngebot() {
    return ausgesetztEigenesAngebot;
  }

  public void setAusgesetztEigenesAngebot(Boolean ausgesetztEigenesAngebot) {
    this.ausgesetztEigenesAngebot = ausgesetztEigenesAngebot;
  }

  public TilgungsWunsch bausparWunsch(BausparWunsch bausparWunsch) {
    this.bausparWunsch = bausparWunsch;
    return this;
  }

   /**
   * Get bausparWunsch
   * @return bausparWunsch
  **/
  @ApiModelProperty(example = "null", value = "")
  public BausparWunsch getBausparWunsch() {
    return bausparWunsch;
  }

  public void setBausparWunsch(BausparWunsch bausparWunsch) {
    this.bausparWunsch = bausparWunsch;
  }

  public TilgungsWunsch rate(BigDecimal rate) {
    this.rate = rate;
    return this;
  }

   /**
   * muss leer sein, wenn eines der anderen Attribute gefüllt ist
   * @return rate
  **/
  @ApiModelProperty(example = "null", value = "muss leer sein, wenn eines der anderen Attribute gefüllt ist")
  public BigDecimal getRate() {
    return rate;
  }

  public void setRate(BigDecimal rate) {
    this.rate = rate;
  }

  public TilgungsWunsch tilgungsBeginn(LocalDate tilgungsBeginn) {
    this.tilgungsBeginn = tilgungsBeginn;
    return this;
  }

   /**
   * Get tilgungsBeginn
   * @return tilgungsBeginn
  **/
  @ApiModelProperty(example = "null", value = "")
  public LocalDate getTilgungsBeginn() {
    return tilgungsBeginn;
  }

  public void setTilgungsBeginn(LocalDate tilgungsBeginn) {
    this.tilgungsBeginn = tilgungsBeginn;
  }

  public TilgungsWunsch tilgungsErsatzProduktId(String tilgungsErsatzProduktId) {
    this.tilgungsErsatzProduktId = tilgungsErsatzProduktId;
    return this;
  }

   /**
   * Get tilgungsErsatzProduktId
   * @return tilgungsErsatzProduktId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTilgungsErsatzProduktId() {
    return tilgungsErsatzProduktId;
  }

  public void setTilgungsErsatzProduktId(String tilgungsErsatzProduktId) {
    this.tilgungsErsatzProduktId = tilgungsErsatzProduktId;
  }

  public TilgungsWunsch volltilgerWennAnnuitaetenOderForward(Boolean volltilgerWennAnnuitaetenOderForward) {
    this.volltilgerWennAnnuitaetenOderForward = volltilgerWennAnnuitaetenOderForward;
    return this;
  }

   /**
   * muss leer sein, wenn eines der anderen Attribute gefüllt ist
   * @return volltilgerWennAnnuitaetenOderForward
  **/
  @ApiModelProperty(example = "false", value = "muss leer sein, wenn eines der anderen Attribute gefüllt ist")
  public Boolean getVolltilgerWennAnnuitaetenOderForward() {
    return volltilgerWennAnnuitaetenOderForward;
  }

  public void setVolltilgerWennAnnuitaetenOderForward(Boolean volltilgerWennAnnuitaetenOderForward) {
    this.volltilgerWennAnnuitaetenOderForward = volltilgerWennAnnuitaetenOderForward;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TilgungsWunsch tilgungsWunsch = (TilgungsWunsch) o;
    return Objects.equals(this.anfaenglicheTilgung, tilgungsWunsch.anfaenglicheTilgung) &&
        Objects.equals(this.ausgesetztBerechnet, tilgungsWunsch.ausgesetztBerechnet) &&
        Objects.equals(this.ausgesetztEigenesAngebot, tilgungsWunsch.ausgesetztEigenesAngebot) &&
        Objects.equals(this.bausparWunsch, tilgungsWunsch.bausparWunsch) &&
        Objects.equals(this.rate, tilgungsWunsch.rate) &&
        Objects.equals(this.tilgungsBeginn, tilgungsWunsch.tilgungsBeginn) &&
        Objects.equals(this.tilgungsErsatzProduktId, tilgungsWunsch.tilgungsErsatzProduktId) &&
        Objects.equals(this.volltilgerWennAnnuitaetenOderForward, tilgungsWunsch.volltilgerWennAnnuitaetenOderForward);
  }

  @Override
  public int hashCode() {
    return Objects.hash(anfaenglicheTilgung, ausgesetztBerechnet, ausgesetztEigenesAngebot, bausparWunsch, rate, tilgungsBeginn, tilgungsErsatzProduktId, volltilgerWennAnnuitaetenOderForward);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TilgungsWunsch {\n");
    
    sb.append("    anfaenglicheTilgung: ").append(toIndentedString(anfaenglicheTilgung)).append("\n");
    sb.append("    ausgesetztBerechnet: ").append(toIndentedString(ausgesetztBerechnet)).append("\n");
    sb.append("    ausgesetztEigenesAngebot: ").append(toIndentedString(ausgesetztEigenesAngebot)).append("\n");
    sb.append("    bausparWunsch: ").append(toIndentedString(bausparWunsch)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("    tilgungsBeginn: ").append(toIndentedString(tilgungsBeginn)).append("\n");
    sb.append("    tilgungsErsatzProduktId: ").append(toIndentedString(tilgungsErsatzProduktId)).append("\n");
    sb.append("    volltilgerWennAnnuitaetenOderForward: ").append(toIndentedString(volltilgerWennAnnuitaetenOderForward)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

