/*
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 1.0
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import de.europace.eli.model.TilgungsWunsch;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * VariablesDarlehensWunsch
 */

public class VariablesDarlehensWunsch {
  @JsonProperty("darlehensBetrag")
  private BigDecimal darlehensBetrag = null;

  @JsonProperty("provision")
  private BigDecimal provision = null;

  @JsonProperty("tilgungsWunsch")
  private TilgungsWunsch tilgungsWunsch = null;

  public VariablesDarlehensWunsch darlehensBetrag(BigDecimal darlehensBetrag) {
    this.darlehensBetrag = darlehensBetrag;
    return this;
  }

   /**
   * Get darlehensBetrag
   * @return darlehensBetrag
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getDarlehensBetrag() {
    return darlehensBetrag;
  }

  public void setDarlehensBetrag(BigDecimal darlehensBetrag) {
    this.darlehensBetrag = darlehensBetrag;
  }

  public VariablesDarlehensWunsch provision(BigDecimal provision) {
    this.provision = provision;
    return this;
  }

   /**
   * Get provision
   * @return provision
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getProvision() {
    return provision;
  }

  public void setProvision(BigDecimal provision) {
    this.provision = provision;
  }

  public VariablesDarlehensWunsch tilgungsWunsch(TilgungsWunsch tilgungsWunsch) {
    this.tilgungsWunsch = tilgungsWunsch;
    return this;
  }

   /**
   * Get tilgungsWunsch
   * @return tilgungsWunsch
  **/
  @ApiModelProperty(required = true, value = "")
  public TilgungsWunsch getTilgungsWunsch() {
    return tilgungsWunsch;
  }

  public void setTilgungsWunsch(TilgungsWunsch tilgungsWunsch) {
    this.tilgungsWunsch = tilgungsWunsch;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VariablesDarlehensWunsch variablesDarlehensWunsch = (VariablesDarlehensWunsch) o;
    return Objects.equals(this.darlehensBetrag, variablesDarlehensWunsch.darlehensBetrag) &&
        Objects.equals(this.provision, variablesDarlehensWunsch.provision) &&
        Objects.equals(this.tilgungsWunsch, variablesDarlehensWunsch.tilgungsWunsch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(darlehensBetrag, provision, tilgungsWunsch);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VariablesDarlehensWunsch {\n");
    
    sb.append("    darlehensBetrag: ").append(toIndentedString(darlehensBetrag)).append("\n");
    sb.append("    provision: ").append(toIndentedString(provision)).append("\n");
    sb.append("    tilgungsWunsch: ").append(toIndentedString(tilgungsWunsch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

