/*
 * Ergebnislisten API
 * Ein Service um eine Ergebnisliste mit Finanzierungsvorschlägen zu ermitteln.
 *
 * OpenAPI spec version: 1.0
 * Contact: helpdesk@europace2.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.europace.eli.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Verbindlichkeit
 */

public class Verbindlichkeit {
  @JsonProperty("glaeubiger")
  private String glaeubiger = null;

  @JsonProperty("laufzeitEnde")
  private LocalDate laufzeitEnde = null;

  @JsonProperty("rateMonatlich")
  private BigDecimal rateMonatlich = null;

  @JsonProperty("restschuld")
  private BigDecimal restschuld = null;

  @JsonProperty("wirdAbgeloest")
  private Boolean wirdAbgeloest = null;

  public Verbindlichkeit glaeubiger(String glaeubiger) {
    this.glaeubiger = glaeubiger;
    return this;
  }

   /**
   * Get glaeubiger
   * @return glaeubiger
  **/
  @ApiModelProperty(value = "")
  public String getGlaeubiger() {
    return glaeubiger;
  }

  public void setGlaeubiger(String glaeubiger) {
    this.glaeubiger = glaeubiger;
  }

  public Verbindlichkeit laufzeitEnde(LocalDate laufzeitEnde) {
    this.laufzeitEnde = laufzeitEnde;
    return this;
  }

   /**
   * Get laufzeitEnde
   * @return laufzeitEnde
  **/
  @ApiModelProperty(value = "")
  public LocalDate getLaufzeitEnde() {
    return laufzeitEnde;
  }

  public void setLaufzeitEnde(LocalDate laufzeitEnde) {
    this.laufzeitEnde = laufzeitEnde;
  }

  public Verbindlichkeit rateMonatlich(BigDecimal rateMonatlich) {
    this.rateMonatlich = rateMonatlich;
    return this;
  }

   /**
   * Get rateMonatlich
   * @return rateMonatlich
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getRateMonatlich() {
    return rateMonatlich;
  }

  public void setRateMonatlich(BigDecimal rateMonatlich) {
    this.rateMonatlich = rateMonatlich;
  }

  public Verbindlichkeit restschuld(BigDecimal restschuld) {
    this.restschuld = restschuld;
    return this;
  }

   /**
   * Get restschuld
   * @return restschuld
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getRestschuld() {
    return restschuld;
  }

  public void setRestschuld(BigDecimal restschuld) {
    this.restschuld = restschuld;
  }

  public Verbindlichkeit wirdAbgeloest(Boolean wirdAbgeloest) {
    this.wirdAbgeloest = wirdAbgeloest;
    return this;
  }

   /**
   * Get wirdAbgeloest
   * @return wirdAbgeloest
  **/
  @ApiModelProperty(value = "")
  public Boolean getWirdAbgeloest() {
    return wirdAbgeloest;
  }

  public void setWirdAbgeloest(Boolean wirdAbgeloest) {
    this.wirdAbgeloest = wirdAbgeloest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Verbindlichkeit verbindlichkeit = (Verbindlichkeit) o;
    return Objects.equals(this.glaeubiger, verbindlichkeit.glaeubiger) &&
        Objects.equals(this.laufzeitEnde, verbindlichkeit.laufzeitEnde) &&
        Objects.equals(this.rateMonatlich, verbindlichkeit.rateMonatlich) &&
        Objects.equals(this.restschuld, verbindlichkeit.restschuld) &&
        Objects.equals(this.wirdAbgeloest, verbindlichkeit.wirdAbgeloest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(glaeubiger, laufzeitEnde, rateMonatlich, restschuld, wirdAbgeloest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Verbindlichkeit {\n");
    
    sb.append("    glaeubiger: ").append(toIndentedString(glaeubiger)).append("\n");
    sb.append("    laufzeitEnde: ").append(toIndentedString(laufzeitEnde)).append("\n");
    sb.append("    rateMonatlich: ").append(toIndentedString(rateMonatlich)).append("\n");
    sb.append("    restschuld: ").append(toIndentedString(restschuld)).append("\n");
    sb.append("    wirdAbgeloest: ").append(toIndentedString(wirdAbgeloest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

